# Generated by Django 6.0.8 on 2026-10-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
        ('tenants', '0040_outlet_staff_discount_limit_pct'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promo',
            name='unique_promo_code_per_tenant',
        ),
        migrations.AddField(
            model_name='promo',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='promo',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', ''), ('archived_at__isnull', True)), fields=('tenant', 'code'), name='unique_promo_code_per_tenant'),
        ),
    ]
