# Generated by Django 6.0.6 on 2026-08-04 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0031_outlet_qr_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('razorpay_payment_link_id', models.CharField(blank=True, default='', max_length=64)),
                ('razorpay_payment_link_url', models.URLField(blank=True, default='')),
                ('razorpay_payment_id', models.CharField(blank=True, default=None, max_length=64, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('overdue_warning_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_invoices', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='billing_sub_tenant__cd4c85_idx'), models.Index(fields=['status', 'period_end'], name='billing_sub_status_e74c2f_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'period_start', 'period_end'), name='unique_invoice_per_tenant_period')],
            },
        ),
    ]
