# Generated by Django 6.0.3 on 2026-03-12 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlet',
            options={'ordering': ['tenant', 'name']},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='outlet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique identifier for the tenant', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Tenant timezone (example: Asia/Kolkata)', max_length=50),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='outlet',
            index=models.Index(fields=['tenant'], name='tenants_out_tenant__bbfde1_idx'),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['slug'], name='tenants_ten_slug_63daca_idx'),
        ),
        migrations.AddConstraint(
            model_name='outlet',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_outlet_per_tenant'),
        ),
    ]
