# Generated by Django 6.0.3 on 2026-03-31 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_outlet_options_alter_tenant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Restaurant Logo for bills', null=True, upload_to='tenant_logos/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='sales_agent',
            field=models.ForeignKey(blank=True, help_text='Superuser/Agent who brought this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_sold', to=settings.AUTH_USER_MODEL),
        ),
    ]
