# Generated by Django 6.0.3 on 2026-04-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_logo_tenant_sales_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(default='default', help_text='Unique identifier for the tenant', unique=True),
            preserve_default=False,
        ),
    ]
