# Generated by Django 6.0.3 on 2026-04-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='email',
            field=models.EmailField(blank=True, help_text='Outlet email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='fssai_no',
            field=models.CharField(blank=True, help_text='FSSAI License Number', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='gst_no',
            field=models.CharField(blank=True, help_text='Restaurant GSTIN (15 characters)', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='phone',
            field=models.CharField(blank=True, help_text='Outlet phone number for bills', max_length=15, null=True),
        ),
    ]
