# Generated by Django 6.0.3 on 2026-04-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_outlet_compliance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='whatsapp_no',
            field=models.CharField(blank=True, help_text='WhatsApp number for sending digital bills', max_length=15, null=True),
        ),
    ]
