# Generated by Django 6.0.3 on 2026-04-30 07:21

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_outlet_whatsapp_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Restaurant Logo for bills', null=True, upload_to='tenant_logos/', validators=[core.validators.validate_image_size]),
        ),
    ]
