# Generated by Django 6.0.3 on 2026-05-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_tenant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='business_day_start_hour',
            field=models.IntegerField(default=6, help_text="Hour (0-23) at which a new business day starts. If it's before this hour, the order belongs to the previous calendar day."),
        ),
    ]
