# Generated by Django 6.0.3 on 2026-05-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_outlet_business_day_start_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='Outlet closing time (e.g. 23:30). Set after midnight for late-night outlets.', null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='Outlet opening time (e.g. 11:00)', null=True),
        ),
    ]
