# Generated by Django 6.0.3 on 2026-05-09 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_outlet_closing_time_outlet_opening_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly subscription fee charged to this tenant', max_digits=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended')], default='trial', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(choices=[('fine_dining', 'Fine Dining'), ('franchise', 'Franchise / QSR'), ('cafe', 'Cafe / Coffee Shop')], default='fine_dining', help_text='Controls which features are visible to the tenant', max_length=20),
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['tenant_type'], name='tenants_ten_tenant__af6352_idx'),
        ),
    ]
