# Generated by Django 6.0.3 on 2026-05-10 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_tenant_subscription_end_date_tenant_subscription_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantFeatureOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(help_text='Feature name (e.g. barcode_transfer, split_bill)', max_length=50)),
                ('enabled', models.BooleanField(default=True, help_text='True to enable, False to explicitly disable')),
                ('notes', models.TextField(blank=True, help_text="Reason for override (e.g. 'Central kitchen needed')")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'feature')},
            },
        ),
    ]
