# Generated by Django 6.0.3 on 2026-05-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenantfeatureoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='sac_code',
            field=models.CharField(blank=True, default='996331', help_text='SAC (Services Accounting Code) under GST. 996331 = Restaurant / café / QSR / food court (correct for most restaurants). 996332 = Delivery / food truck. 996334 = Catering. Change only if your CA specifies a different code.', max_length=8),
        ),
    ]
