# Generated by Django 6.0.3 on 2026-05-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_add_sac_code_to_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='gst_inclusive',
            field=models.BooleanField(default=False, help_text='True  → menu prices already include GST. Bill back-calculates and shows GST inside the price.          Example: Coffee ₹25 — GST (5%) ₹1.19 included. Customer pays ₹25 exactly.          Use this for QSRs, cafés, and Zomato/Swiggy restaurants. False → GST is added on top of menu prices at billing (default).          Example: Coffee ₹23.81 + GST ₹1.19 = ₹25.          Use this for fine dining and hotels.'),
        ),
    ]
