# Generated by Django 6.0.3 on 2026-05-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_add_gst_inclusive_to_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='is_composition_scheme',
            field=models.BooleanField(default=False, help_text="True → Composition Scheme dealer. Bill header shows 'Bill of Supply'. No CGST/SGST lines on printed bill. Legal note added to CSV exports only."),
        ),
        migrations.AddField(
            model_name='outlet',
            name='split_bill_by_category',
            field=models.BooleanField(default=False, help_text='True → Counter Billing Mode. After payment, prints one slip per menu category (e.g. Breakfast, Juice, Tea) with partial cuts between them. Customer carries each slip to the relevant counter. Used in food courts and multi-section hotels.'),
        ),
    ]
