# Generated by Django 6.0.3 on 2026-05-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_outlet_composition_and_split_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='parcel_charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra charge added for parcel/takeaway orders. Set to 0 to disable. Shown as a separate line on the bill.', max_digits=6),
        ),
    ]
