# Generated by Django 6.0.3 on 2026-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_outlet_parcel_charge_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='parcel_charge_per_item',
            field=models.BooleanField(default=True, help_text='True (recommended): charge × quantity (3 idlis = ₹15). False: flat charge per order regardless of items.'),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='parcel_charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Packaging charge per item for parcel/takeaway orders. Set to 0 to disable. Example: ₹5 per item — 3 items = ₹15 parcel charge total.', max_digits=6),
        ),
    ]
