# Generated by Django 6.0.3 on 2026-05-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_outlet_parcel_per_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='use_qz_tray',
            field=models.BooleanField(default=False, help_text='Use QZ Tray for USB printing with real partial/full cuts. Requires QZ Tray installed on the billing laptop. Falls back to browser print if QZ Tray is not running.'),
        ),
    ]
