# Generated by Django 6.0.3 on 2026-05-23 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_qz_tray_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tenant',
            name='tenants_ten_slug_63daca_idx',
        ),
        migrations.AlterField(
            model_name='outlet',
            name='fssai_no',
            field=models.CharField(blank=True, help_text='FSSAI License Number (14 digits)', max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='FSSAI licence number must be exactly 14 digits.', regex='^\\d{14}$')]),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='gst_no',
            field=models.CharField(blank=True, help_text='Restaurant GSTIN (15 characters, e.g. 29ABCDE1234F1Z5)', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid 15-character GSTIN (e.g. 29ABCDE1234F1Z5).', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')]),
        ),
    ]
