# Generated by Django 6.0.3 on 2026-05-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_remove_tenant_tenants_ten_slug_63daca_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='agent_host',
            field=models.CharField(default='localhost', help_text="'localhost' when the Rasova Agent runs on this device (Windows PC or Termux on tablet). Set to a local IP (e.g. 192.168.1.200) when using a Raspberry Pi or separate print server.", max_length=253),
        ),
        migrations.AddField(
            model_name='outlet',
            name='paper_width_mm',
            field=models.IntegerField(choices=[(58, '58mm — narrow roll'), (80, '80mm — standard roll')], default=80, help_text='Thermal paper width. Most restaurant printers use 80mm.'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='printer_mac',
            field=models.CharField(blank=True, help_text='Thermal printer MAC address (e.g. 00:1B:44:11:3A:B7). Printed on the sticker on the bottom of the printer. Used to locate the printer automatically even if its IP changes.', max_length=17),
        ),
    ]
