# Generated by Django 6.0.3 on 2026-05-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_outlet_printer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='font_scale',
            field=models.FloatField(default=1.0, help_text='UI font scale multiplier. 1.0 = default size. 1.1 = 10% larger (good for large-screen kiosks). 0.9 = 10% smaller (laptops with limited space).'),
        ),
    ]
