# Generated by Django 6.0.3 on 2026-05-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_tenant_font_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='is_union_territory',
            field=models.BooleanField(default=False, help_text='True → Outlet is in a Union Territory (Delhi, J&K, Chandigarh, Puducherry, Daman & Diu, etc.). Invoices will show UTGST instead of SGST as required by GST law.'),
        ),
    ]
