# Generated by Django 6.0.3 on 2026-05-27 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0022_outlet_print_agent_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='print_agent_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secret key the Rasova Agent uses to poll for print jobs. Never share publicly.', unique=True),
        ),
    ]
