# Generated by Django 6.0.3 on 2026-06-19 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0025_outlet_outlet_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantFeatureAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=50)),
                ('enabled', models.BooleanField()),
                ('source', models.CharField(help_text="'override' or 'default' (reset to type default)", max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_audit_log', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['tenant', 'feature'], name='tenants_ten_tenant__d83a93_idx')],
            },
        ),
    ]
