# Generated by Django 6.0.3 on 2026-07-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0028_fix_orphan_theme_columns_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantfeatureauditlog',
            name='source',
            field=models.CharField(help_text="'override' or 'default' (reset to type default), or 'preset:<key>'", max_length=50),
        ),
    ]
