# Generated by Django 6.0.7 on 2026-08-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0032_outlet_is_central_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='po_vendor_email_enabled',
            field=models.BooleanField(default=False, help_text="True → automatically email a PDF copy of a purchase order to the vendor when a manager marks it as ordered. Off by default: sending email on a tenant's behalf on a vendor's real inbox needs explicit opt-in, not an assumed default."),
        ),
    ]
