# Generated by Django 6.0.8 on 2026-09-27 15:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0033_outlet_po_vendor_email_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='parcel_gst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text="GST on the parcel charge, in percent. Packing is part of the restaurant service, so it carries the food's rate: 5% for most restaurants, 18% in a hotel with rooms over ₹7,500 a night. Added on top when prices exclude GST, taken out of the charge when they include it, and never charged on the composition scheme.", max_digits=5),
        ),
    ]
