# Generated by Django 6.0.8 on 2026-09-27 22:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0034_parcel_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='liquor_billing_mode',
            field=models.CharField(choices=[('one_bill', 'One bill, food and liquor in two sections'), ('two_bills', 'A separate bill for liquor')], db_default='one_bill', default='one_bill', max_length=10),
        ),
        migrations.AddField(
            model_name='outlet',
            name='vat_inclusive',
            field=models.BooleanField(db_default=False, default=False, help_text='True: liquor menu prices already include VAT. Separate from GST inclusive, because many bars price food with tax added and drinks with tax included, or the other way round.'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='vat_registration_no',
            field=models.CharField(blank=True, db_default='', default='', help_text='State VAT registration (TIN) number, printed on the liquor part of the bill.', max_length=20),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='parcel_gst_rate',
            field=models.DecimalField(db_default=Decimal('5.00'), decimal_places=2, default=Decimal('5.00'), help_text="GST on the parcel charge, in percent. Packing is part of the restaurant service, so it carries the food's rate: 5% for most restaurants, 18% in a hotel with rooms over ₹7,500 a night. Added on top when prices exclude GST, taken out of the charge when they include it, and never charged on the composition scheme.", max_digits=5),
        ),
    ]
