# Generated by Django 6.0.8 on 2026-09-28 18:19

import re

import django.core.validators
from django.db import migrations, models


def _suggest(name, taken):
    # Frozen copy of tenants.models.suggest_bill_code: a migration never reads
    # app code that may change later.
    words = re.findall(r"[A-Za-z0-9]+", name or "")
    base = ("".join(word[0] for word in words) if len(words) > 1 else "".join(words))[:3].upper() or "R"
    if base not in taken:
        return base
    for n in range(2, 1000):
        candidate = base[:3 - len(str(n))] + str(n)
        if candidate not in taken:
            return candidate
    raise ValueError(f"no free bill number code for {name!r}")


def give_every_outlet_a_bill_code(apps, schema_editor):
    """Every existing outlet gets a code from its restaurant's name ("Spice
    Garden" -> "SG"), different from its sister outlets' ("SG2")."""
    Outlet = apps.get_model("tenants", "Outlet")
    codes = {}
    for outlet in Outlet.objects.select_related("tenant").filter(bill_code="").order_by("tenant_id", "outlet_number", "id"):
        taken = codes.setdefault(outlet.tenant_id, set(
            Outlet.objects.filter(tenant_id=outlet.tenant_id).exclude(bill_code="").values_list("bill_code", flat=True)))
        outlet.bill_code = _suggest(outlet.tenant.name, taken)
        taken.add(outlet.bill_code)
        outlet.save(update_fields=["bill_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0036_demo_outlet_sample_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='bill_code',
            field=models.CharField(blank=True, db_default='', default='', help_text="Starts this outlet's bill numbers, as in SG/2627/000123: up to 3 letters or digits, different for each outlet of the restaurant. Set from the restaurant's name when the outlet is made; changing it starts a new series.", max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z0-9]{1,3}$', 'A bill number code is up to 3 capital letters or digits, like SG.')]),
        ),
        migrations.RunPython(give_every_outlet_a_bill_code, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='outlet',
            constraint=models.UniqueConstraint(condition=models.Q(('bill_code', ''), _negated=True), fields=('tenant', 'bill_code'), name='unique_bill_code_per_tenant'),
        ),
    ]
