# Generated by Django 6.0.8 on 2026-10-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0037_outlet_bill_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='is_union_territory',
            field=models.BooleanField(default=False, help_text='True: the outlet is in a union territory without a legislature (Chandigarh, Ladakh, Lakshadweep, Andaman and Nicobar, Dadra and Nagar Haveli and Daman and Diu), so bills show UTGST instead of SGST. Delhi, Puducherry and Jammu and Kashmir charge SGST. Used only when the outlet has no GSTIN; a GSTIN decides it.'),
        ),
    ]
