# Generated by Django 6.0.8 on 2026-10-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0038_union_territory_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(choices=[('fine_dining', 'Fine Dining'), ('franchise', 'Franchise / QSR'), ('cafe', 'Cafe / Coffee Shop'), ('pub', 'Pub / Bar')], default='fine_dining', help_text='Controls which features are visible to the tenant', max_length=20),
        ),
    ]
