# Generated by Django 6.0.8 on 2026-10-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0039_pub_tenant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='staff_discount_limit_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The largest discount a cashier or captain may give on their own, as a percent of the bill (a free dish counts as 100%). Above it, a manager or the owner has to apply it. Blank = no limit.', max_digits=5, null=True),
        ),
    ]
