# Generated by Django 6.0.3 on 2026-03-30 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
        ('tenants', '0002_alter_outlet_options_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_enabled', models.BooleanField(default=True)),
                ('upi_enabled', models.BooleanField(default=True)),
                ('card_enabled', models.BooleanField(default=False)),
                ('cash_label', models.CharField(default='Cash', max_length=50)),
                ('upi_label', models.CharField(default='UPI / GPay', max_length=50)),
                ('card_label', models.CharField(default='Card', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_config', to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Payment Configuration',
            },
        ),
    ]
