# Generated by Django 6.0.3 on 2026-04-08 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_paymentconfig'),
        ('tenants', '0003_tenant_logo_tenant_sales_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zomato_enabled', models.BooleanField(default=False)),
                ('swiggy_enabled', models.BooleanField(default=False)),
                ('uber_eats_enabled', models.BooleanField(default=False)),
                ('zomato_webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('swiggy_webhook_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_accept_orders', models.BooleanField(default=True, help_text='Automatically accept online orders and send KOT to kitchen')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregator_config', to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
    ]
