# Generated by Django 6.0.3 on 2026-04-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_aggregatorconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenstation',
            name='printer_ip',
            field=models.GenericIPAddressField(blank=True, help_text='IP of the thermal printer for this station', null=True),
        ),
        migrations.AddField(
            model_name='kitchenstation',
            name='printer_port',
            field=models.IntegerField(default=9100),
        ),
    ]
