# Generated by Django 6.0.3 on 2026-05-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_printer_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfig',
            name='upi_id',
            field=models.CharField(blank=True, default='', help_text='UPI ID (VPA) shown as QR on bill — e.g. myrestaurant@okaxis', max_length=100),
        ),
    ]
