# Generated by Django 6.0.3 on 2026-05-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchenstation',
            name='printer_name',
            field=models.CharField(blank=True, default='', help_text="Windows printer name for QZ Tray USB printing (e.g. 'BillTouch ZY306'). Find it in Windows → Printers & Scanners.", max_length=200),
        ),
    ]
