# Generated by Django 6.0.3 on 2026-06-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_qz_tray_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfig',
            name='razorpay_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='razorpay_key_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='razorpay_key_secret',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='razorpay_webhook_secret',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
