# Generated by Django 6.0.3 on 2026-06-25 17:28

import core.fields
from django.db import migrations


class Migration(migrations.Migration):
    """
    Switches razorpay_key_secret/razorpay_webhook_secret to encrypted
    storage. Any value saved before this migration was plaintext and is
    NOT re-encrypted in place (by explicit decision, not oversight) — it's
    cleared instead, since attempting to "encrypt" old plaintext through a
    blanket migration risks silently mismatching whatever a given Razorpay
    dashboard actually has on file. Tenants who'd already entered Razorpay
    credentials need to re-enter them once via the setup page; from that
    point on they're stored encrypted.
    """

    dependencies = [
        ('setup', '0008_razorpay_gateway'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE setup_paymentconfig SET razorpay_key_secret = '', razorpay_webhook_secret = '';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='razorpay_key_secret',
            field=core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentconfig',
            name='razorpay_webhook_secret',
            field=core.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
    ]
