# Generated by Django 6.0.3 on 2026-07-11 17:37

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_encrypt_razorpay_secrets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aggregatorconfig',
            name='swiggy_webhook_secret',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aggregatorconfig',
            name='zomato_webhook_secret',
            field=core.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
