# Generated by Django 6.0.8 on 2026-10-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_scheduledreportsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatorconfig',
            name='swiggy_gstin',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='aggregatorconfig',
            name='uber_eats_gstin',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='aggregatorconfig',
            name='zomato_gstin',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
