# Generated by Django 6.0.8 on 2026-10-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_aggregator_operator_gstins'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfig',
            name='upi_instructions',
            field=models.TextField(blank=True, default='', help_text='Shown next to the QR. Leave blank for the standard instructions.'),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='upi_payee_name',
            field=models.CharField(blank=True, default='', help_text='Name the customer sees in their UPI app after scanning', max_length=100),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='upi_qr_image',
            field=models.FileField(blank=True, null=True, upload_to='payment_qr/'),
        ),
    ]
