# Generated by Django 6.0.3 on 2026-03-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('waiter', 'Waiter'), ('chef', 'Chef')], default='cashier', max_length=20),
        ),
    ]
