# Generated by Django 6.0.3 on 2026-03-14 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('tenants', '0002_alter_outlet_options_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
    ]
