# Generated by Django 6.0.3 on 2026-04-17 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_outlet_alter_user_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('agent', 'Agent'), ('cashier', 'Cashier'), ('waiter', 'Waiter'), ('chef', 'Chef')], default='cashier', max_length=20),
        ),
    ]
