# Generated by Django 6.0.3 on 2026-04-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0004_alter_tenant_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['owner', 'manager', 'agent', 'cashier', 'waiter', 'chef'])), name='valid_user_role'),
        ),
    ]
