# Generated by Django 6.0.3 on 2026-05-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_bugfix_cascade_index_constraints'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0018_remove_tenant_tenants_ten_slug_63daca_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('agent', 'Agent'), ('cashier', 'Cashier'), ('waiter', 'Waiter'), ('chef', 'Chef'), ('kitchen', 'Kitchen Staff')], default='cashier', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['outlet'], name='user_outlet'),
        ),
    ]
