# Generated by Django 6.0.3 on 2026-07-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role_user_user_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('agent', 'Agent'), ('cashier', 'Cashier'), ('captain', 'Captain'), ('waiter', 'Waiter'), ('chef', 'Chef'), ('kitchen', 'Kitchen Staff')], default='cashier', max_length=20),
        ),
    ]
