"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()  # Load environment variables from .env file

# -------------------------------------------------------
# SENTRY — initialise as early as possible, before apps
# -------------------------------------------------------
import sentry_sdk
_SENTRY_DSN = os.getenv("SENTRY_DSN", "")
if _SENTRY_DSN:
    sentry_sdk.init(
        dsn=_SENTRY_DSN,
        traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.1")),
        send_default_pii=False,
    )


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "SECRET_KEY environment variable is not set. "
        "Generate one with: python -c \"from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())\""
    )
BASE_URL = os.getenv('BASE_URL', 'http://localhost:8000')

# Default keeps /admin/ for local dev; production sets ADMIN_URL to an
# unguessable path so the login page isn't sitting at the one URL every
# scanner tries first.
ADMIN_URL = os.getenv('ADMIN_URL', 'admin/')

# Lets /live-demo/?key=<this> skip the public-visitor restrictions (demo
# trailer mode) for the one person who actually knows it -- a bookmarked
# link instead of a password, since the demo account has no usable password
# at all (see demo_seed.py). Unset in an environment means the key can never
# match, so the fail-safe default is "everyone is a restricted visitor."
DEMO_FOUNDER_KEY = os.getenv('DEMO_FOUNDER_KEY', '')

# Encrypts at-rest secrets stored in the database (e.g. PaymentConfig's
# Razorpay key/webhook secrets). Required in every environment, same as
# SECRET_KEY — a missing key must never silently fall back to plaintext.
FIELD_ENCRYPTION_KEY = os.getenv('FIELD_ENCRYPTION_KEY')
if not FIELD_ENCRYPTION_KEY:
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "FIELD_ENCRYPTION_KEY environment variable is not set. "
        "Generate one with: python -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
    )
# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False — production must explicitly opt in to DEBUG via env var.
# A missing/misspelled DEBUG var must never silently expose tracebacks + secrets.
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Single-restaurant install on a Windows PC (setup.bat / start.bat): served
# over plain http on the shop's own network by waitress, data in SQLite next
# to the code. Turns off what only makes sense for the hosted rasova.net
# service (https-only cookies, *.rasova.net cookie domain, subdomain
# redirects, the PostgreSQL requirement) while DEBUG stays off.
_LOCAL_INSTALL_PC = os.getenv('LOCAL_INSTALL', 'False') == 'True'
# The test suite checks the hosted behaviour, whatever this PC's .env says
# (it still may use this PC's SQLite database, see the db guard below).
LOCAL_INSTALL = _LOCAL_INSTALL_PC and not (len(__import__('sys').argv) > 1 and __import__('sys').argv[1] == 'test')

# Structural tenant isolation (core/models.py TenantManager): auto-scopes
# every TenantScopedModel query to the current request's tenant instead of
# relying on every call site to remember an explicit filter. Deploys here
# are a hard `systemctl restart`, not rolling, so there's no mixed-version
# window to reason about -- but there's also no fast rollback besides a
# full redeploy, and this flag IS that fast rollback. Meant to be removed
# on a dated follow-up once there's a stable production window, not kept
# indefinitely.
TENANT_AUTO_SCOPE_ENABLED = os.getenv('TENANT_AUTO_SCOPE_ENABLED', 'True') == 'True'

# Parse comma-separated hosts, fallback to localhost for dev
env_hosts = os.getenv('ALLOWED_HOSTS', '')
if env_hosts:
    ALLOWED_HOSTS = [host.strip() for host in env_hosts.split(',') if host.strip()]
else:
    from django.core.exceptions import ImproperlyConfigured
    if not DEBUG:
        raise ImproperlyConfigured("ALLOWED_HOSTS must be set in production via environment variable.")
    ALLOWED_HOSTS = ['*']  # dev only — production requires ALLOWED_HOSTS env var

# The main site's host. Marketing pages are indexable only here; see
# core.middleware.SearchIndexingMiddleware.
CANONICAL_HOST = os.getenv('CANONICAL_HOST', 'rasova.net')

# Cloudflare / reverse-proxy: trust forwarded headers for HTTPS detection
USE_X_FORWARDED_HOST    = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    'jazzmin',  # admin theme; must come before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    # Third-party
    'axes',
    # Internal apps
    'accounts',
    'menu',
    'orders',
    'reports',
    'tenants',
    'inventory',
    'notifications',
    'setup',
    'shifts',
    'crm',
    'finance',
    'promos',
    'offers',
    'printing',
    'tokens',
    'kitchen',
    'waiter',
    'tablemerge',
    'payments',
    'agency',
    'billing',
    'devtools',
    'royal_shetkari',
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Before WhiteNoise, so it also covers the marketing pages it serves
    'core.middleware.SearchIndexingMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Subdomain → tenant resolution (reads request.get_host())
    'core.middleware.TenantMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # django-axes must come after AuthenticationMiddleware
    'axes.middleware.AxesMiddleware',
    # Needs request.user (auth) + request.tenant (TenantMiddleware, above)
    'core.middleware.SubscriptionStatusMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.ContextLoggingMiddleware',
    'core.middleware.NoStoreForAuthenticatedResponsesMiddleware',
    'core.middleware.RequestLoggingMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': DEBUG,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
		'core.context_processors.base_url',
                'core.context_processors.tenant_features',
            ],
            **({} if DEBUG else {
                'loaders': [
                    ('django.template.loaders.cached.Loader', [
                        'django.template.loaders.filesystem.Loader',
                        'django.template.loaders.app_directories.Loader',
                    ]),
                ],
            }),
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }




DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
        'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
    }
}

# The SQLite default above is for local use only; see core/db_guard.py.
from core.db_guard import require_postgres_in_production  # noqa: E402
require_postgres_in_production(
    DATABASES['default']['ENGINE'], DEBUG, os.getenv('ALLOW_NON_POSTGRES') == '1' or _LOCAL_INSTALL_PC,
)



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# WhiteNoise serves files from public/ at the root URL (/)
# index.html in public/ is served at exactly / (the landing page)
WHITENOISE_ROOT        = BASE_DIR / 'public'
WHITENOISE_INDEX_FILE  = True
if LOCAL_INSTALL:
    # The restaurant's own PC opens straight on its login page, not the
    # rasova.net marketing site in public/ (core.views.landing redirects).
    WHITENOISE_ROOT = None

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# -------------------------------------------------------
# MEDIA STORAGE — S3 via django-storages
# Set AWS_STORAGE_BUCKET_NAME in env to enable S3 storage.
# Falls back to local disk for development.
# -------------------------------------------------------
_is_test_run = len(__import__('sys').argv) > 1 and __import__('sys').argv[1] == 'test'
_static_backend = (
    "django.contrib.staticfiles.storage.StaticFilesStorage"  # no manifest needed in tests
    if _is_test_run
    else "core.storage.ManifestStaticStorage"
)

_AWS_BUCKET = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
if _AWS_BUCKET:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": _static_backend,
        },
    }
    AWS_STORAGE_BUCKET_NAME = _AWS_BUCKET
    AWS_ACCESS_KEY_ID       = os.getenv("AWS_ACCESS_KEY_ID", "")
    AWS_SECRET_ACCESS_KEY   = os.getenv("AWS_SECRET_ACCESS_KEY", "")
    # R2 ignores region, but boto3 needs a value — "auto" works for Cloudflare R2.
    AWS_S3_REGION_NAME      = os.getenv("AWS_S3_REGION_NAME", "auto")
    # Cloudflare R2 (or any S3-compatible store): point this at the R2 endpoint,
    # e.g. https://<ACCOUNT_ID>.r2.cloudflarestorage.com  (blank = real AWS S3)
    AWS_S3_ENDPOINT_URL     = os.getenv("AWS_S3_ENDPOINT_URL", "") or None
    AWS_S3_FILE_OVERWRITE   = False
    AWS_DEFAULT_ACL         = None      # R2 has no ACLs — public access is via the bucket's public domain
    AWS_QUERYSTRING_AUTH    = False     # serve plain public URLs, not signed/expiring ones
    AWS_S3_CUSTOM_DOMAIN    = os.getenv("AWS_S3_CUSTOM_DOMAIN", "")
    if AWS_S3_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/"
    elif AWS_S3_ENDPOINT_URL:
        MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"
    else:
        MEDIA_URL = f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/"
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": _static_backend,
        },
    }

# Cookie name Django's CSRF middleware sets and every template's JS reads
# back out of document.cookie. Deliberately NOT gated behind `if not DEBUG`
# like the domain-scoping settings below it -- a cookie's NAME has no
# environment-specific meaning (unlike its domain/secure/scope), so it must
# match in every environment, or the hardcoded `csrftoken2` reads in every
# template's JS (purchase_orders.html, inventory_board.html, and 7 others)
# find nothing and either throw (a bare `.find(...).split('=')[1]` on
# undefined) or silently send no token at all -- confirmed breaking local
# DEBUG-mode testing of the Order/Edit/Receive flows on this exact page.
CSRF_COOKIE_NAME = "csrftoken2"

# Security Headers
if LOCAL_INSTALL and not DEBUG:
    # Plain http on the restaurant's own network: cookies can't be https-only
    # and stay scoped to the exact host (localhost or the PC's LAN address).
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SESSION_COOKIE_HTTPONLY = True
    _raw_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _raw_csrf_origins.split(',') if o.strip()]
elif not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Wildcard covers all tenant subdomains (https://*.rasova.net)
    # Falls back to env var for custom domains
    _raw_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://*.rasova.net,https://rasova.net')
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _raw_csrf_origins.split(',') if o.strip()]

    # Without an explicit cookie domain, a cookie is scoped to the EXACT host
    # that set it. auth_views.py redirects a user from the apex/login host to
    # their tenant's own subdomain (tenant-slug.rasova.net) after login — a
    # user who authenticates anywhere other than that exact subdomain (the
    # apex domain, or a host TenantMiddleware didn't resolve) would silently
    # not have their session cookie sent to the subdomain they're redirected
    # to. The leading dot makes the cookie valid for the base domain AND every
    # tenant subdomain, matching CSRF_TRUSTED_ORIGINS's wildcard above.
    _cookie_domain = os.environ.get('SESSION_COOKIE_DOMAIN', '.rasova.net')
    SESSION_COOKIE_DOMAIN = _cookie_domain
    CSRF_COOKIE_DOMAIN = _cookie_domain

    # CSRF_COOKIE_NAME is set unconditionally above (not here) -- see that
    # comment. The rename itself was originally motivated by exactly this
    # domain-scoping change: any browser that had already logged in BEFORE
    # the domain-wide cookie above was deployed still had an old csrftoken
    # cookie scoped to the exact host (e.g. spice.rasova.net) alongside the
    # new one scoped to .rasova.net. Both were valid, both got sent, and the
    # JS reading document.cookie and Django's own request.COOKIES parsing
    # weren't guaranteed to pick the same one of the two — producing a
    # persistent, unexplained "CSRF token from header incorrect" 403 on
    # every POST from that browser, confirmed in logs/security.log
    # recurring across several days on one staff device, that clearing
    # cookies once didn't reliably fix. Renaming the cookie made every
    # browser fetch one single, unambiguous new cookie on its next request.

    # Tell Django the real scheme when running behind nginx or any reverse proxy.
    # Without this, Django sees all requests as HTTP and HTTPS-detection breaks.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True          # allow HSTS preload list submission
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # Django-level HTTP→HTTPS redirect. OFF by default: when Cloudflare runs in
    # "Flexible" SSL mode (or nginx forwards X-Forwarded-Proto: http), enabling
    # this creates an infinite redirect loop (ERR_TOO_MANY_REDIRECTS) because
    # Django keeps seeing the proxied request as insecure.
    # Only enable (SECURE_SSL_REDIRECT=True in env) once Cloudflare is in "Full"
    # mode AND the origin correctly sends X-Forwarded-Proto: https.
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "False") == "True"

# Default primary key field type

AUTH_USER_MODEL = 'accounts.User'

# -------------------------------------------------------
# AUTHENTICATION BACKENDS — axes must be last
# -------------------------------------------------------
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'axes.backends.AxesStandaloneBackend',
]

# -------------------------------------------------------
# DJANGO-AXES — brute-force login protection
# -------------------------------------------------------
AXES_FAILURE_LIMIT = int(os.getenv("AXES_FAILURE_LIMIT", "5"))  # lockout after 5 failures
AXES_COOLOFF_TIME = 1  # hours before account is unlocked automatically
AXES_LOCKOUT_CALLABLE = None  # use default 403 response
AXES_RESET_ON_SUCCESS = True  # clear failure count on successful login
AXES_USERNAME_FORM_FIELD = "username"
AXES_ENABLE_ADMIN = False  # don't lock admin separately

# Behind Cloudflare -> Nginx, request.META['REMOTE_ADDR'] is always Nginx's
# own loopback connection (127.0.0.1), never the real visitor. Axes (login
# lockouts) and django-ratelimit both ask core.utils.get_client_ip, which
# believes a forwarded header only from a machine trusted to have set it.
AXES_CLIENT_IP_CALLABLE = "core.utils.get_client_ip"
RATELIMIT_IP_META_KEY = "core.utils.get_client_ip"

# The proxies in front of gunicorn whose X-Real-IP is believed (nginx, on
# the same machine).
TRUSTED_PROXY_IPS = [
    ip.strip() for ip in os.getenv("TRUSTED_PROXY_IPS", "127.0.0.1,::1").split(",") if ip.strip()
]

# Cloudflare's own addresses: CF-Connecting-IP is believed only from these.
# From https://www.cloudflare.com/ips-v4 and /ips-v6, checked 1 Oct 2026.
# If Cloudflare adds a range, set CLOUDFLARE_IP_RANGES in .env (comma-separated).
_CLOUDFLARE_IP_RANGES = (
    "173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,"
    "108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,"
    "162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22,"
    "2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,"
    "2a06:98c0::/29,2c0f:f248::/32"
)
CLOUDFLARE_IP_RANGES = [
    cidr.strip()
    for cidr in os.getenv("CLOUDFLARE_IP_RANGES", _CLOUDFLARE_IP_RANGES).split(",")
    if cidr.strip()
]

# Friendly recovery page instead of Django's bare default 403 on a CSRF
# failure (stale token after the tab's been open a while, the exact class
# of bug the csrftoken2 rename fixed the recurring case of). Returns clean
# JSON for fetch()/apiClient calls, an HTML reload page for real navigation.
CSRF_FAILURE_VIEW = "core.views.csrf_failure"


_LOG_DIR = BASE_DIR / "logs"
_LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "filters": {
        "tenant_outlet": {
            "()": "core.log_filters.TenantOutletFilter",
        },
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },

    "formatters": {
        # Short format for console during development
        "simple": {
            "format": "[{levelname}] {name}: {message}",
            "style": "{",
        },
        # Full format for all file handlers
        "verbose": {
            "format": (
                "[{levelname}] {asctime} pid={process:d} "
                "[T:{tenant_id}|O:{outlet_id}|X:{trace_id}] {name} {message}"
            ),
            "style": "{",
        },
        # Request-specific format (no tenant filter — uses its own fields)
        "request_fmt": {
            "format": (
                "[{levelname}] {asctime} {message}"
            ),
            "style": "{",
        },
    },

    "handlers": {
        # ── Console ──────────────────────────────────────────────
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "filters": ["tenant_outlet"],
            "level": "DEBUG",
        },

        # ── Main application log (all POS events) ────────────────
        "pos_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(_LOG_DIR / "pos.log"),
            "maxBytes": 10 * 1024 * 1024,   # 10 MB
            "backupCount": 10,
            "formatter": "verbose",
            "filters": ["tenant_outlet"],
            "level": "DEBUG",
            "encoding": "utf-8",
        },

        # ── Errors only (WARNING+) ───────────────────────────────
        "error_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(_LOG_DIR / "errors.log"),
            "maxBytes": 5 * 1024 * 1024,    # 5 MB
            "backupCount": 10,
            "formatter": "verbose",
            "filters": ["tenant_outlet"],
            "level": "WARNING",
            "encoding": "utf-8",
        },

        # ── Django framework / request log ───────────────────────
        "django_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(_LOG_DIR / "django.log"),
            "maxBytes": 10 * 1024 * 1024,
            "backupCount": 7,
            "formatter": "request_fmt",
            "level": "INFO",
            "encoding": "utf-8",
        },

        # ── Security events (login failures, CSRF, etc.) ─────────
        "security_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(_LOG_DIR / "security.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 10,
            "formatter": "request_fmt",
            "level": "DEBUG",
            "encoding": "utf-8",
        },
    },

    "loggers": {
        # ── Django internal loggers ───────────────────────────────
        "django": {
            "handlers": ["django_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["django_file", "error_file"],
            "level": "WARNING",   # logs 4xx/5xx with full tracebacks
            "propagate": False,
        },
        "django.security": {
            "handlers": ["security_file", "error_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        # CSRF 403s after login are expected (token rotates on auth) — suppress in dev
        "django.security.csrf": {
            "handlers": ["security_file"],
            "level": "WARNING" if not DEBUG else "ERROR",
            "propagate": False,
        },
        "django.db.backends": {
            # Set to DEBUG to log every SQL query; INFO to suppress
            "handlers": ["pos_file"],
            "level": "INFO",
            "propagate": False,
        },

        # ── POS application loggers ───────────────────────────────
        "pos": {
            # Root POS logger — all pos.* namespaces inherit this
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.notifications": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.menu": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.orders": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.inventory": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.reports": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.billing": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.auth": {
            "handlers": ["security_file", "pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.setup": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.core": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.shifts": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
        "pos.crm": {
            "handlers": ["pos_file", "error_file", "console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Tests never write to the real log files. They filled logs/ with test
# tenants' events, and under `manage.py test --parallel` the workers all
# rotated the same files, which Windows refuses ("being used by another
# process"), printing a "Logging error" block each time. The console handler
# stays, and assertLogs works as before (it adds its own handler).
import sys as _sys
if len(_sys.argv) > 1 and _sys.argv[1] == "test":
    for _name, _handler in LOGGING["handlers"].items():
        if "filename" in _handler:
            LOGGING["handlers"][_name] = {"class": "logging.NullHandler"}

# Aggregator webhook IP allowlist: addresses or ranges (CIDR), comma-separated.
AGGREGATOR_IP_ALLOWLIST = [
    ip.strip() for ip in os.getenv('AGGREGATOR_IP_ALLOWLIST', '127.0.0.1').split(',') if ip.strip()
]
# How far a webhook's signed timestamp may be from now (orders/services/aggregator_webhook.py).
AGGREGATOR_WEBHOOK_MAX_AGE_SECONDS = int(os.getenv('AGGREGATOR_WEBHOOK_MAX_AGE_SECONDS', '300'))

# -------------------------------------------------------
# AUTH REDIRECT
# Django's @login_required defaults to /accounts/login/ which 404s.
# Set LOGIN_URL to the actual login view.
# -------------------------------------------------------
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

# -------------------------------------------------------
# WHATSAPP RECEIPTS
# Backend 1 (preferred): Meta WhatsApp Business Cloud API — free 1000 msg/month
#   META_WHATSAPP_TOKEN    = your permanent system user token
#   META_WHATSAPP_PHONE_ID = phone number ID from Meta Business dashboard
# Backend 2 (fallback): Twilio
#   TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_WHATSAPP_FROM
# Leave all blank to disable silently.
# -------------------------------------------------------
META_WHATSAPP_TOKEN   = os.getenv("META_WHATSAPP_TOKEN", "")
META_WHATSAPP_PHONE_ID = os.getenv("META_WHATSAPP_PHONE_ID", "")

TWILIO_ACCOUNT_SID   = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN    = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_WHATSAPP_FROM = os.getenv("TWILIO_WHATSAPP_FROM", "whatsapp:+14155238886")

# -------------------------------------------------------
# RASOVA'S OWN RAZORPAY ACCOUNT -- for charging tenants their Rasova
# subscription fee. Deliberately named distinctly from anything tenant-
# facing (PaymentConfig's per-tenant razorpay_key_id/secret) so the two
# are never confused in config, mirroring the code-level separation in
# billing/razorpay_gateway.py vs payments/razorpay_gateway.py.
# -------------------------------------------------------
RASOVA_RAZORPAY_KEY_ID = os.getenv("RASOVA_RAZORPAY_KEY_ID", "")
RASOVA_RAZORPAY_KEY_SECRET = os.getenv("RASOVA_RAZORPAY_KEY_SECRET", "")
RASOVA_RAZORPAY_WEBHOOK_SECRET = os.getenv("RASOVA_RAZORPAY_WEBHOOK_SECRET", "")

# -------------------------------------------------------
# EMAIL
# Dev:  set EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend in .env
#       → emails print to terminal, no Gmail needed
# Prod: set EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
#       + EMAIL_USER and EMAIL_PASSWORD (Gmail App Password)
# -------------------------------------------------------
EMAIL_BACKEND  = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend" if DEBUG
    else "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST          = "smtp.gmail.com"
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = os.getenv("EMAIL_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD", "")
DEFAULT_FROM_EMAIL  = os.getenv("EMAIL_USER", "noreply@rasova.net")

# -------------------------------------------------------
# SESSION — long enough for a full 12-hour QSR shift.
# SESSION_EXPIRE_AT_BROWSER_CLOSE removed:
#   Tablets used as POS terminals rarely close the browser tab.
#   With it set to True, sessions expired silently when the browser
#   process briefly restarted (e.g. tablet sleep → wake). Staff would
#   hit /token/X/bill/ and see "Order not found" because @login_required
#   was redirecting to /accounts/login/ (404) instead of /login/.
# -------------------------------------------------------
SESSION_COOKIE_AGE = 86400  # 24 hours — restaurants run 18-hour shifts

# -------------------------------------------------------
# CACHE + SESSION ENGINE — adapts to whether Redis is
# available in this environment.
#
# REDIS_URL defaults to "" (empty) so local dev WITHOUT
# redis running does not crash.  Set REDIS_URL in .env
# for production (required for multi-worker session sharing).
#
# With Redis:    RedisCache + cached_db sessions  → multi-worker safe
# Without Redis: LocMemCache + db sessions        → single-worker only
#                (dev / demo laptop — perfectly fine)
# -------------------------------------------------------
REDIS_URL = os.getenv("REDIS_URL", "")

import sys as _sys
_TESTING = len(_sys.argv) > 1 and _sys.argv[1] == "test"
_HAS_REDIS = bool(REDIS_URL) and not _TESTING

if _HAS_REDIS:
    CACHES = {
        "default": {
            "BACKEND":  "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "TIMEOUT":  300,
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.db"

# django-ratelimit: when the cache is unavailable (Redis down, tests, etc.)
# fail OPEN — allow the request rather than returning a 500.
# This prevents the login page from crashing when Redis is not running.
#
# SECURITY TRADE-OFF: while Redis is down, ALL rate limits (login, order
# creation, payment) are bypassed. During that window brute-force protection
# relies solely on django-axes account lockout (5 failures → 1h lockout).
# Keeping fail-open is the right call (a Redis blip must not 500 the login
# page), but be aware the rate-limit layer is best-effort, not a hard guarantee.
RATELIMIT_FAIL_OPEN = True

# django-ratelimit's counters live in CACHES["default"], which — unlike the
# database — is NOT rolled back between individual TestCase methods. A full
# `manage.py test` run (locally or in CI) shares one cache for its entire
# process, so hundreds of tests hitting a rate-limited endpoint (create_order
# is 20/min per IP) across the whole suite exhaust real production limits
# and start returning spurious 403s to unrelated, later tests — confirmed
# repeatedly this session (orders.tests.test_qr_reorder passes cleanly
# in isolation, only fails when run as part of a large combined suite).
# No test anywhere asserts on an actual rate-limit 403/429 (confirmed by
# grep), so disabling it under the test runner only is a no-op for coverage
# and removes a source of CI flakiness that was blocking auto-deploy.
RATELIMIT_ENABLE = not _TESTING

CELERY_BROKER_URL = REDIS_URL or "redis://127.0.0.1:6379/0"
# A local install has no Redis: run background tasks (printing, alerts) in
# the web process instead of trying to reach a broker that isn't there.
if LOCAL_INSTALL and not REDIS_URL:
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = False
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"
CELERY_RESULT_EXTENDED = True

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Kolkata"

# If Redis is unreachable, fall back gracefully instead of crashing the request.
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 3

# Printing tasks should be fast; kill them if they run over 60 seconds.
CELERY_TASK_SOFT_TIME_LIMIT = 30   # raises SoftTimeLimitExceeded
CELERY_TASK_TIME_LIMIT      = 60   # hard kill after 60s

# Two queues: default for everything, printing for thermal printer tasks.
# This lets you prioritise print jobs without blocking other tasks.
CELERY_TASK_ROUTES = {
    "orders.tasks.print_kot_task":  {"queue": "printing"},
    "orders.tasks.print_bill_task": {"queue": "printing"},
}

CELERY_TASK_DEFAULT_QUEUE = "default"

# Acknowledge tasks AFTER completion, not on receipt.
# If the worker crashes mid-task, the task is re-queued for the next worker.
# Combined with idempotency keys in tasks.py this prevents both lost tasks
# and double-printing.
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# Discard tasks queued more than 30 minutes ago — stale print jobs from a
# previous session should not print when the worker restarts.
CELERY_TASK_EXPIRES = 1800  # seconds

# Scheduled tasks (celery beat). Hardcoded rather than django_celery_beat --
# nothing here needs a per-tenant custom schedule *time*, only per-tenant
# recipients/opt-in, which is what setup.ScheduledReportSubscription is for.
# "Daily at 7am" against CELERY_TIMEZONE (Asia/Kolkata, above) works because
# every tenant today is India-based; revisit if that ever stops being true.
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    "daily-report-digest": {
        "task": "reports.tasks.send_daily_digest_email",
        "schedule": crontab(hour=7, minute=0),
    },
    # Rasova's own subscription billing (charging tenants, not tenant-facing).
    # See md_files/eli5_subscription_billing_plan.html for the full design.
    "generate-monthly-subscription-invoices": {
        "task": "billing.tasks.generate_monthly_invoices",
        "schedule": crontab(hour=6, minute=0),  # before the daily digest
    },
    "enforce-overdue-subscriptions": {
        "task": "billing.tasks.enforce_overdue_subscriptions",
        "schedule": crontab(hour=6, minute=30),
    },
    # Public /live-demo/ tenant: wipe whatever a visitor did every few hours
    # so the next one always lands on a clean floor plan, without anyone
    # needing to remember to run reset_demo_tenant by hand.
    "reset-public-demo-tenant": {
        "task": "orders.tasks.reset_demo_tenant_task",
        "schedule": crontab(minute=0, hour="*/2"),
    },
}


# -------------------------------------------------------
# Admin theme (django-jazzmin)
# -------------------------------------------------------
JAZZMIN_SETTINGS = {
    "site_title": "Royal Shetkari",
    "site_header": "Royal Shetkari",
    "site_brand": "Royal Shetkari",
    "site_logo": "img/royal_shetkari_mark.svg",
    "login_logo": "img/royal_shetkari_mark.svg",
    "site_logo_classes": "img-circle",
    "site_icon": "img/royal_shetkari_mark.svg",
    "welcome_sign": "Royal Shetkari",
    "copyright": "Royal Shetkari",
    "search_model": ["orders.Order", "menu.MenuItem", "accounts.User"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Admin home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Open POS", "url": "/dashboard/", "new_window": False},
        {"model": "orders.Order"},
        {"model": "menu.MenuItem"},
    ],
    "usermenu_links": [
        {"name": "Open POS", "url": "/dashboard/", "icon": "fas fa-cash-register"},
    ],
    "show_sidebar": True,
    "navigation_expanded": False,
    "hide_apps": ["django_celery_results"],
    "order_with_respect_to": [
        "orders", "menu", "kitchen", "tokens", "inventory", "finance",
        "offers", "promos", "accounts", "auth", "tenants", "setup",
        "printing", "notifications", "waiter", "billing", "royal_shetkari",
    ],
    "icons": {
        "orders": "fas fa-receipt",
        "menu": "fas fa-utensils",
        "kitchen": "fas fa-fire",
        "tokens": "fas fa-ticket-alt",
        "inventory": "fas fa-boxes",
        "finance": "fas fa-wallet",
        "offers": "fas fa-percent",
        "promos": "fas fa-tags",
        "accounts": "fas fa-user-tie",
        "tenants": "fas fa-store",
        "setup": "fas fa-cogs",
        "printing": "fas fa-print",
        "notifications": "fas fa-bell",
        "waiter": "fas fa-concierge-bell",
        "billing": "fas fa-file-invoice-dollar",
        "royal_shetkari": "fas fa-seedling",
        "auth": "fas fa-users-cog",
        "auth.Group": "fas fa-users",
        "accounts.User": "fas fa-user-tie",
        "billing.SubscriptionInvoice": "fas fa-file-invoice-dollar",
        "finance.Expense": "fas fa-wallet",
        "inventory.InventoryItem": "fas fa-boxes",
        "inventory.Recipe": "fas fa-book-open",
        "kitchen.DailyKOTCounter": "fas fa-sort-numeric-up",
        "kitchen.KOTBatch": "fas fa-fire",
        "kitchen.KitchenMessage": "fas fa-comment-dots",
        "menu.MenuCategory": "fas fa-layer-group",
        "menu.MenuItem": "fas fa-utensils",
        "menu.MenuItemModifierGroup": "fas fa-link",
        "menu.ModifierGroup": "fas fa-sliders-h",
        "notifications.Notification": "fas fa-bell",
        "offers.Offer": "fas fa-percent",
        "orders.Order": "fas fa-receipt",
        "orders.Payment": "fas fa-credit-card",
        "orders.Table": "fas fa-chair",
        "printing.PrintJob": "fas fa-print",
        "promos.Promo": "fas fa-tags",
        "royal_shetkari.DemoRecord": "fas fa-seedling",
        "setup.KitchenStation": "fas fa-fire-alt",
        "setup.ScheduledReportSubscription": "fas fa-envelope-open-text",
        "tenants.Outlet": "fas fa-store",
        "tenants.PrintProfile": "fas fa-file-alt",
        "tenants.Tenant": "fas fa-building",
        "tenants.TenantFeatureAuditLog": "fas fa-history",
        "tenants.TenantFeatureOverride": "fas fa-toggle-on",
        "tokens.DailyOnlineTokenCounter": "fas fa-globe",
        "tokens.DailyTokenCounter": "fas fa-ticket-alt",
        "tokens.TokenOrder": "fas fa-hashtag",
        "waiter.WaiterCall": "fas fa-concierge-bell",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "css/admin_theme.css",
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"accounts.User": "collapsible", "auth.group": "vertical_tabs"},
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "default_theme_mode": "dark",
    "navbar": "navbar-dark",
    "navbar_fixed": True,
    "sidebar": "sidebar-dark-warning",
    "sidebar_fixed": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_flat_style": True,
    "accent": "accent-warning",
    "brand_colour": "navbar-dark",
    "footer_fixed": False,
    "actions_sticky_top": True,
    "button_classes": {
        "primary": "btn-warning",
        "secondary": "btn-outline-light",
        "info": "btn-outline-light",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-warning",
    },
}
