# Generated by Django 6.0.8 on 2026-10-03 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0016_liquor_vat'),
        ('tenants', '0040_outlet_staff_discount_limit_pct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Shown on the bill, e.g. 'Buy 2 pitchers, get 1 free'.", max_length=80)),
                ('kind', models.CharField(choices=[('buy_get_free', 'Buy N, get M free'), ('percent_off', '% off'), ('amount_off', 'Rs off each')], max_length=20)),
                ('buy_qty', models.PositiveSmallIntegerField(blank=True, help_text='Buy N: the units paid for.', null=True)),
                ('free_qty', models.PositiveSmallIntegerField(default=1, help_text='Get M free: the cheapest M of each group.')),
                ('percent', models.DecimalField(blank=True, decimal_places=2, help_text='% off: off each covered dish.', max_digits=5, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Rs off each covered dish (never more than its price).', max_digits=10, null=True)),
                ('priority', models.SmallIntegerField(default=0, help_text='When two offers could take the same dish, the higher priority is tried first.')),
                ('valid_from', models.DateField(blank=True, help_text='First business day it runs.', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Last business day it runs.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('paused_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(blank=True, help_text='Leave blank for every outlet of this restaurant.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OfferTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menucategory')),
                ('menu_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='offers.offer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(blank=True, default='', help_text='Business-day weekdays as digits, Monday 0 to Sunday 6, e.g. 01234 for Mon-Fri. Blank: every day.', max_length=7)),
                ('start_time', models.TimeField(blank=True, help_text='Blank: from the start of the business day.', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Blank: to the end of the business day. Before the start: past midnight.', null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='offers.offer')),
            ],
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['tenant', 'is_active'], name='offer_tenant_active'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('percent__isnull', True), models.Q(('percent__gt', 0), ('percent__lte', 100)), _connector='OR'), name='offer_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__isnull', True), ('amount__gt', 0), _connector='OR'), name='offer_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='offertarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('menu_item__isnull', False)), models.Q(('category__isnull', False), ('menu_item__isnull', True)), _connector='OR'), name='offer_target_one_of'),
        ),
    ]
