# Generated by Django 6.0.3 on 2026-03-31 09:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_tenant_logo_tenant_sales_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clocked_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clocked_out_at', models.DateTimeField(blank=True, null=True)),
                ('tips', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-clocked_in_at'],
                'indexes': [models.Index(fields=['tenant', 'outlet', 'staff'], name='shifts_shif_tenant__7a6881_idx'), models.Index(fields=['clocked_in_at'], name='shifts_shif_clocked_4daed2_idx')],
            },
        ),
    ]
