# Generated by Django 6.0.3 on 2026-05-12 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_shifttemplate_staffschedule'),
        ('tenants', '0011_tenantfeatureoverride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('outlet',), name='one_open_session_per_outlet'),
        ),
    ]
