# Generated by Django 6.0.3 on 2026-05-23 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_bugfix_cascade_index_constraints'),
        ('tenants', '0018_remove_tenant_tenants_ten_slug_63daca_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsession',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cashsession',
            index=models.Index(fields=['tenant', 'outlet', 'date'], name='cashsession_outlet_date'),
        ),
    ]
