# Generated by Django 6.0.3 on 2026-03-12 18:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_recipe_unit_alter_inventoryitem_unit'),
        ('menu', '0003_menuitemmodifiergroup'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('restock', 'Restock'), ('consume', 'Consumption'), ('wastage', 'Wastage'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='quantity_required',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('menu_item', 'inventory_item')},
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['tenant', 'outlet'], name='inventory_i_tenant__5428e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='inventory_stock_non_negative'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['tenant', 'outlet'], name='inventory_i_tenant__b61ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['item'], name='inventory_i_item_id_a5cd26_idx'),
        ),
    ]
