# Generated by Django 6.0.3 on 2026-04-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_recipe_quantity_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost price per unit', max_digits=10),
        ),
    ]
