# Generated by Django 6.0.3 on 2026-05-08 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_last_purchase_price_and_more'),
        ('tenants', '0008_outlet_business_day_start_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPOCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='inventory.supplier'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('tenant', 'outlet', 'supplier'), name='unique_draft_po_per_supplier'),
        ),
        migrations.AddField(
            model_name='tenantpocounter',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet'),
        ),
        migrations.AddField(
            model_name='tenantpocounter',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantpocounter',
            unique_together={('tenant', 'outlet')},
        ),
    ]
