# Generated by Django 6.0.3 on 2026-05-09 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_tenantpocounter_alter_purchaseorder_supplier_and_more'),
        ('tenants', '0010_tenant_subscription_end_date_tenant_subscription_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches_sent', to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BatchTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('received', 'Received'), ('partial', 'Partially Received')], default='pending', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('destination_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='tenants.outlet')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='inventory.productionbatch')),
            ],
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters')], max_length=20)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.productionbatch')),
            ],
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['tenant', 'source_outlet'], name='inventory_p_tenant__1897ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productionbatch',
            unique_together={('tenant', 'batch_number')},
        ),
        migrations.AddIndex(
            model_name='batchtransfer',
            index=models.Index(fields=['tenant', 'destination_outlet', 'status'], name='inventory_b_tenant__08ffa5_idx'),
        ),
    ]
