# Generated by Django 6.0.3 on 2026-05-17 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_productionbatch_batchtransfer_batchitem_and_more'),
        ('tenants', '0012_add_sac_code_to_outlet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved — Ready to Fulfill'), ('in_production', 'In Production (CK Processing)'), ('ordered', 'Ordered from Vendor'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('route', models.CharField(choices=[('auto', 'Auto-route'), ('internal', 'Central Kitchen'), ('external', 'Vendor PO'), ('split', 'Split (CK + Vendor)')], default='auto', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_created', to=settings.AUTH_USER_MODEL)),
                ('fulfilling_outlet', models.ForeignKey(blank=True, help_text='Central kitchen outlet that will fulfill this (if internal)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions_to_fulfill', to='tenants.outlet')),
                ('production_batch', models.ForeignKey(blank=True, help_text='Set when CK converts this requisition to a batch', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productionbatch')),
                ('purchase_order', models.ForeignKey(blank=True, help_text='Set when converted to a vendor PO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.purchaseorder')),
                ('requesting_outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitions_raised', to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantity_approved', models.DecimalField(blank=True, decimal_places=3, help_text='CK can adjust this before approving', max_digits=12, null=True)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters')], max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockrequisition')),
            ],
        ),
        migrations.AddIndex(
            model_name='stockrequisition',
            index=models.Index(fields=['tenant', 'requesting_outlet', 'status'], name='inventory_s_tenant__2a8d66_idx'),
        ),
        migrations.AddIndex(
            model_name='stockrequisition',
            index=models.Index(fields=['tenant', 'fulfilling_outlet', 'status'], name='inventory_s_tenant__384323_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='requisitionitem',
            unique_together={('requisition', 'inventory_item')},
        ),
    ]
