# Generated by Django 6.0.3 on 2026-05-23 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_add_stock_requisition'),
        ('tenants', '0018_remove_tenant_tenants_ten_slug_63daca_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchitem',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='batchitem',
            name='barcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='batchitem',
            unique_together={('tenant', 'barcode')},
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['item', 'created_at'], name='invtxn_item_date'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['tenant', 'outlet', 'created_at'], name='invtxn_outlet_date'),
        ),
    ]
