# Generated by Django 6.0.3 on 2026-06-03 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_batchitem_tenant_alter_batchitem_barcode_and_more'),
        ('menu', '0015_menuitem_parcel_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'Pieces'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters')], default='ml', max_length=10)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_recipes', to='inventory.inventoryitem')),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_links', to='menu.modifier')),
            ],
            options={
                'unique_together': {('modifier', 'inventory_item')},
            },
        ),
    ]
