# Generated by Django 6.0.3 on 2026-07-12 06:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_modifierrecipe'),
        ('tenants', '0028_fix_orphan_theme_columns_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='batch_type',
            field=models.CharField(choices=[('produce', 'Produced — new goods from ingredients'), ('move', 'Moved — existing kitchen stock leaves')], default='produce', help_text="'move' debits the central kitchen's own stock when the batch is dispatched; 'produce' does not (the goods are newly made).", max_length=10),
        ),
        migrations.AddConstraint(
            model_name='batchtransfer',
            constraint=models.UniqueConstraint(fields=('tenant', 'batch', 'destination_outlet'), name='unique_transfer_per_batch_destination'),
        ),
    ]
