# Generated by Django 6.0.3 on 2026-07-13 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_productionbatch_batch_type_and_more'),
        ('menu', '0015_menuitem_parcel_charge'),
        ('tenants', '0028_fix_orphan_theme_columns_not_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready_for_review', 'Ready for Review'), ('confirmed', 'Confirmed'), ('discarded', 'Discarded'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('raw_extraction', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_import_jobs', to='menu.menuitem')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeImportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('raw_ingredient_name', models.CharField(blank=True, max_length=255)),
                ('raw_quantity_text', models.CharField(blank=True, max_length=100)),
                ('extracted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extracted_unit', models.CharField(blank=True, choices=[('pcs', 'Pieces'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters')], max_length=10, null=True)),
                ('needs_manual_quantity', models.BooleanField(default=False)),
                ('match_method', models.CharField(choices=[('exact', 'Exact name match'), ('fuzzy', 'Fuzzy match'), ('ai', 'AI-resolved'), ('new', 'No match — new ingredient'), ('manual', 'Manually added by reviewer')], max_length=10)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('is_new_ingredient', models.BooleanField(default=False)),
                ('final_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_unit', models.CharField(blank=True, choices=[('pcs', 'Pieces'), ('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters')], max_length=10, null=True)),
                ('include_in_recipe', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.recipeimportjob')),
                ('resolved_inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventoryitem')),
                ('suggested_inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='recipeimportjob',
            index=models.Index(fields=['tenant', 'outlet', 'status'], name='inventory_r_tenant__ae8732_idx'),
        ),
    ]
