# Generated by Django 6.0.3 on 2026-07-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_recipeimportjob_recipeimportline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
