# Generated by Django 6.0.7 on 2026-08-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventoryitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='invoiced_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What the vendor actually charged at receive time, if different from unit_price (the ordered price). Null until received, or if the price matched exactly.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, default=0, help_text='How much of this line has actually arrived so far. Can be less than quantity — a delivery can be partial or split across more than one receipt.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
