# Generated by Django 6.0.7 on 2026-08-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_purchaseorderitem_invoiced_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='emailed_at',
            field=models.DateTimeField(blank=True, help_text='Set only once the vendor email actually sends (not just attempted).', null=True),
        ),
    ]
