# Generated by Django 6.0.8 on 2026-09-24 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_purchaseorder_emailed_at'),
        ('orders', '0060_delete_payments_models_state_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.orderitem'),
        ),
    ]
