"""
Maintainer tool (not run by setup.bat): downloads one photo per dish from
Wikimedia Commons into royal_shetkari/assets/menu_images/ and records its
author, licence and source page in royal_shetkari/assets/menu_images/credits.json.

Only licences that allow commercial reuse are accepted: CC0, public domain,
CC BY and CC BY-SA (any version). Each picture keeps its attribution in
credits.json and in IMAGE_CREDITS.md (generated by --write-md).

A dish with no suitable photo of its own gets a "representative" photo of
the same kind of food (match="representative"); a dish with nothing at all
gets a generated placeholder card (match="placeholder"), clearly labelled.

Usage (from the project root, needs internet):
    .venv\\Scripts\\python royal_shetkari\\tools\\fetch_menu_images.py
    .venv\\Scripts\\python royal_shetkari\\tools\\fetch_menu_images.py --only misal --force
    .venv\\Scripts\\python royal_shetkari\\tools\\fetch_menu_images.py --write-md
"""
import argparse
import html
import io
import json
import re
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from PIL import Image, ImageDraw, ImageFont  # noqa: E402

from royal_shetkari.seed.menu_data import all_dishes  # noqa: E402
from royal_shetkari.seed.image_queries import queries_for  # noqa: E402

OUT = ROOT / "royal_shetkari" / "assets" / "menu_images"
CREDITS = OUT / "credits.json"
UA = "RoyalShetkariPOS-ImageSeeder/1.0 (local restaurant demo; contact via project owner)"
SIZE = (640, 480)

OK_LICENSE = re.compile(r"^(cc0|cc-zero|public domain|pd|cc by(-sa)? ?\d(\.\d)?|cc-by(-sa)?-\d(\.\d)?)", re.I)
BAD_LICENSE = re.compile(r"(nc|nd|non-?commercial|no ?deriv|fair use|gfdl only)", re.I)
BAD_TITLE = re.compile(r"(logo|map|diagram|menu card|packet|label|poster|\.svg|\.gif|\.tif|\.pdf|\.webm|\.ogv|signboard|statue)", re.I)


def _get(url, tries=4):
    for attempt in range(tries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            with urllib.request.urlopen(req, timeout=40) as resp:
                return resp.read()
        except Exception as exc:  # network hiccup or rate limit: back off
            if attempt == tries - 1:
                raise
            time.sleep(2 + attempt * 3)
            last = exc  # noqa: F841


def strip_html(text):
    return html.unescape(re.sub(r"<[^>]+>", "", text or "")).strip()


OPENVERSE = "https://api.openverse.org/v1/images/"
WIKIPEDIA = "https://en.wikipedia.org/w/api.php"
_openverse_blocked = False


def _thumb(url):
    """A 960px (standard size) version of an upload.wikimedia.org original, else the URL."""
    m = re.match(r"https://upload\.wikimedia\.org/wikipedia/commons/([0-9a-f])/([0-9a-f]{2})/([^/?]+)$", url or "")
    if m and m.group(3).lower().endswith((".jpg", ".jpeg", ".png")):
        a, ab, name = m.groups()
        return f"https://upload.wikimedia.org/wikipedia/commons/thumb/{a}/{ab}/{name}/960px-{name}"
    return url


def search_openverse(query, limit=12):
    """Openverse (WordPress.org's index of openly licensed media: Wikimedia
    Commons, Flickr, museums...). Only licences allowing commercial reuse."""
    global _openverse_blocked
    if _openverse_blocked:
        return []
    params = {"q": query, "license": "cc0,pdm,by,by-sa", "page_size": str(limit),
              "extension": "jpg,jpeg,png", "mature": "false"}
    try:
        data = json.loads(_get(OPENVERSE + "?" + urllib.parse.urlencode(params), tries=2))
    except urllib.error.HTTPError as exc:
        if exc.code == 429:
            print("  (Openverse rate limit reached; using Wikipedia from here on)")
            _openverse_blocked = True
        return []
    out = []
    for r in data.get("results", []):
        lic = (r.get("license") or "").lower()
        ver = r.get("license_version") or ""
        lic_name = {"cc0": "CC0", "pdm": "Public domain"}.get(lic, f"CC {lic.upper()} {ver}".strip())
        out.append({
            "title": r.get("title") or r.get("id"),
            "mime": "image/png" if (r.get("filetype") or "").lower() == "png" else "image/jpeg",
            "width": r.get("width") or 800, "height": r.get("height") or 600,
            "thumb": _thumb(r.get("url")),
            "page": r.get("foreign_landing_url") or "",
            "license": lic_name, "license_url": r.get("license_url") or "",
            "author": (r.get("creator") or "Unknown author")[:200],
            "provider": r.get("source") or r.get("provider") or "",
        })
    return out


def search_wikipedia(query, limit=6):
    """Lead images of matching English Wikipedia articles (files hosted on
    Wikimedia Commons), with their licence from the file's metadata."""
    params = {"action": "query", "format": "json", "generator": "search", "gsrsearch": query,
              "gsrlimit": str(limit), "prop": "pageimages", "piprop": "name"}
    data = json.loads(_get(WIKIPEDIA + "?" + urllib.parse.urlencode(params)))
    pages = sorted((data.get("query") or {}).get("pages", {}).values(), key=lambda p: p.get("index", 99))
    files = [p["pageimage"] for p in pages if p.get("pageimage")]
    if not files:
        return []
    params = {"action": "query", "format": "json", "titles": "|".join("File:" + f for f in files),
              "prop": "imageinfo", "iiprop": "url|extmetadata|size|mime", "iiurlwidth": "960"}
    data = json.loads(_get(WIKIPEDIA + "?" + urllib.parse.urlencode(params)))
    by_title = {p["title"]: p for p in (data.get("query") or {}).get("pages", {}).values()}
    norm = {n["from"]: n["to"] for n in (data.get("query") or {}).get("normalized", [])}
    out = []
    for f in files:
        page = by_title.get(norm.get("File:" + f, "File:" + f))
        if not page or not page.get("imageinfo"):
            continue
        info = page["imageinfo"][0]
        meta = info.get("extmetadata", {})
        out.append({
            "title": page["title"], "mime": info.get("mime", ""),
            "width": info.get("width", 0), "height": info.get("height", 0),
            "thumb": info.get("thumburl") or info.get("url"),
            "page": info.get("descriptionurl", ""),
            "license": strip_html(meta.get("LicenseShortName", {}).get("value", "")),
            "license_url": meta.get("LicenseUrl", {}).get("value", ""),
            "author": strip_html(meta.get("Artist", {}).get("value", ""))[:200] or "Unknown author",
            "provider": "wikimedia",
        })
    return out


PREFER_WIKIPEDIA = False


def search(query):
    if PREFER_WIKIPEDIA:
        return search_wikipedia(query) + search_openverse(query)
    return search_openverse(query) + search_wikipedia(query)


GENERIC_WORDS = {"with", "and", "veg", "dry", "special", "masala", "curry", "fry", "style", "indian", "food",
                 "dish", "pcs", "glass", "the", "fresh", "home", "plain"}


def relevant(query, r):
    """The photo's title (or source page name) mentions a real word of the query."""
    words = [w for w in re.findall(r"[a-z]+", query.lower()) if len(w) >= 3 and w not in GENERIC_WORDS]
    if not words:
        return True
    hay = (r["title"] + " " + urllib.parse.unquote(r.get("page", ""))).lower()
    return any(w in hay for w in words)


def acceptable(r):
    if r["mime"] not in ("image/jpeg", "image/png"):
        return False
    if BAD_TITLE.search(r["title"]):
        return False
    if r["width"] < 400 or r["height"] < 300:
        return False
    lic = r["license"]
    return bool(OK_LICENSE.search(lic)) and not BAD_LICENSE.search(lic)


def to_card(raw):
    img = Image.open(io.BytesIO(raw)).convert("RGB")
    w, h = img.size
    target = SIZE[0] / SIZE[1]
    if w / h > target:
        nw = int(h * target)
        img = img.crop(((w - nw) // 2, 0, (w - nw) // 2 + nw, h))
    else:
        nh = int(w / target)
        img = img.crop((0, (h - nh) // 2, w, (h - nh) // 2 + nh))
    img = img.resize(SIZE, Image.LANCZOS)
    out = io.BytesIO()
    img.save(out, "JPEG", quality=82, optimize=True, progressive=True)
    return out.getvalue()


def placeholder(dish):
    """A clearly labelled placeholder card (own work, no third-party rights)."""
    img = Image.new("RGB", SIZE, (96, 40, 20) if not dish["is_veg"] else (34, 84, 44))
    d = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype("arial.ttf", 40)
        small = ImageFont.truetype("arial.ttf", 22)
    except OSError:
        font = small = ImageFont.load_default()
    d.text((40, 170), dish["name"], fill="white", font=font)
    d.text((40, 240), dish["category"], fill=(230, 230, 230), font=small)
    d.text((40, 420), "PLACEHOLDER IMAGE - replace with a real photo", fill=(255, 220, 120), font=small)
    out = io.BytesIO()
    img.save(out, "JPEG", quality=85)
    return out.getvalue()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", help="substring of dish slug to (re)fetch")
    ap.add_argument("--force", action="store_true", help="refetch even if the file exists")
    ap.add_argument("--reject", help="comma-separated dish slugs whose current photo is wrong: never use it again, refetch")
    ap.add_argument("--write-md", action="store_true", help="only regenerate IMAGE_CREDITS.md")
    ap.add_argument("--prefer-wikipedia", action="store_true",
                    help="try English Wikipedia article photos before Openverse")
    ap.add_argument("--no-fallback", action="store_true",
                    help="only the dish's own search terms; no representative photo (placeholder instead)")
    args = ap.parse_args()
    global PREFER_WIKIPEDIA
    PREFER_WIKIPEDIA = args.prefer_wikipedia

    OUT.mkdir(parents=True, exist_ok=True)
    credits = json.loads(CREDITS.read_text(encoding="utf-8")) if CREDITS.exists() else {}

    rejected = set(credits.get("_rejected", []))
    if args.reject:
        slugs = [x.strip() for x in args.reject.split(",") if x.strip()]
        for slug in slugs:
            if credits.get(slug, {}).get("title"):
                rejected.add(credits[slug]["title"])
            credits.pop(slug, None)
        credits["_rejected"] = sorted(rejected)
        CREDITS.write_text(json.dumps(credits, indent=1, ensure_ascii=False), encoding="utf-8")
        args.force = False
        only = set(slugs)
    else:
        only = None

    if not args.write_md:
        used_titles = {c.get("title") for k, c in credits.items() if not k.startswith("_") and c.get("title")}
        for dish in all_dishes():
            slug = dish["image_slug"]
            if args.only and args.only not in slug:
                continue
            if only is not None and slug not in only:
                continue
            path = OUT / f"{slug}.jpg"
            if path.exists() and slug in credits and not args.force:
                continue
            if args.force and credits.get(slug, {}).get("title"):
                used_titles.discard(credits[slug]["title"])
            chosen = None
            for match, query in queries_for(dish):
                if args.no_fallback and match != "dish":
                    continue
                try:
                    results = search(query)
                except Exception as exc:
                    print(f"  ! search failed for {query!r}: {exc}")
                    continue
                for r in results:
                    if (not acceptable(r) or r["title"] in used_titles or r["title"] in rejected
                            or not relevant(query, r)):
                        continue
                    try:
                        path.write_bytes(to_card(_get(r["thumb"], tries=2)))
                    except Exception as exc:
                        print(f"  ! download failed for {r['title']}: {exc}")
                        continue
                    chosen = (match, query, r)
                    break
                if chosen:
                    break
                time.sleep(1.5)
            if chosen:
                match, query, r = chosen
            if chosen:
                used_titles.add(r["title"])
                credits[slug] = {
                    "dish": dish["name"], "match": match, "query": query, "title": r["title"],
                    "author": r["author"], "license": r["license"], "license_url": r["license_url"],
                    "source": r["page"], "provider": r.get("provider", ""),
                    "modified": "cropped to 4:3 and resized to 640x480",
                }
                print(f"{match:15} {dish['name']:40} <- {r['title']} [{r['license']}]")
            else:
                path.write_bytes(placeholder(dish))
                credits[slug] = {"dish": dish["name"], "match": "placeholder", "author": "Generated by fetch_menu_images.py",
                                 "license": "Own work (project placeholder)", "source": ""}
                print(f"{'placeholder':15} {dish['name']}")
            CREDITS.write_text(json.dumps(credits, indent=1, ensure_ascii=False), encoding="utf-8")
            time.sleep(1.5)

    write_md(credits)


def write_md(credits):
    lines = [
        "# Menu image credits",
        "",
        "Every dish picture in `royal_shetkari/assets/menu_images/` is listed here with its",
        "source, author and licence. Photos come from Wikimedia Commons under licences that",
        "allow commercial reuse with attribution (CC0, public domain, CC BY, CC BY-SA). Each was",
        "cropped to 4:3 and resized to 640x480; CC BY-SA images remain under CC BY-SA.",
        "",
        "Match types:",
        "- **dish**: a photo of that dish.",
        "- **representative**: a photo of a closely related dish or the same style of food, used",
        "  because no free photo of the exact dish was found. Replace with your own photo when you can.",
        "- **placeholder**: a generated card with the dish name, no photo. Replace before going live.",
        "",
        "| Dish | Match | Author | Licence | Source |",
        "|---|---|---|---|---|",
    ]
    for dish in all_dishes():
        c = credits.get(dish["image_slug"], {})
        author = (c.get("author") or "").replace("|", "/").replace("\n", " ")
        src = f"[{c.get('title', 'source')}]({c['source']})" if c.get("source") else "-"
        lines.append(f"| {dish['name']} | {c.get('match', 'missing')} | {author} | {c.get('license', '')} | {src} |")
    counts = {}
    for c in (credits.get(d["image_slug"], {}) for d in all_dishes()):
        counts[c.get("match")] = counts.get(c.get("match"), 0) + 1
    lines += ["", "Totals: " + ", ".join(f"{k}: {v}" for k, v in sorted(counts.items(), key=lambda kv: str(kv[0])))]
    (ROOT / "royal_shetkari" / "IMAGE_CREDITS.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote IMAGE_CREDITS.md", counts)


if __name__ == "__main__":
    main()
