# Generated by Django 6.0.3 on 2026-05-08 07:15

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_guestfeedback'),
        ('orders', '0034_promo'),
        ('tenants', '0009_outlet_closing_time_outlet_opening_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed'])), fields=('tenant', 'outlet', 'table', 'reservation_time'), name='unique_active_reservation_per_table_time'),
        ),
    ]
