"""
Search terms used by royal_shetkari/tools/fetch_menu_images.py to find a
freely licensed photo for each dish on Wikimedia Commons.

queries_for(dish) yields (match, query): "dish" queries look for the dish
itself; "representative" queries fall back to the same style of food.
"""

# Better search terms for dishes whose menu name is not how photos are titled.
DISH_QUERIES = {
    "Puneri Misal Pav": ["Misal pav", "Misal"],
    "Kolhapuri Misal Pav": ["Kolhapuri misal", "Misal Kolhapur"],
    "Pithla Bhakri": ["Pithla bhakri", "Pitla bhakri", "Pithla"],
    "Zunka Bhakar": ["Zunka bhakar", "Zunka"],
    "Bharli Vangi": ["Bharli vangi", "Stuffed brinjal curry", "Bharwa baingan"],
    "Thalipeeth": ["Thalipeeth", "Thalipith"],
    "Sabudana Khichdi": ["Sabudana khichdi", "Sabudana khichadi"],
    "Kanda Poha": ["Kanda poha", "Poha"],
    "Kothimbir Vadi": ["Kothimbir vadi", "Kothimbir wadi"],
    "Alu Vadi": ["Alu vadi", "Patra food", "Patrode"],
    "Shev Bhaji": ["Shev bhaji", "Sev bhaji", "Sev tameta"],
    "Matki Usal": ["Matki usal", "Usal sprouts", "Matki"],
    "Puran Poli": ["Puran poli", "Puranpoli"],
    "Varan Bhaat": ["Varan bhaat", "Varan bhat", "Dal rice ghee"],
    "Jowar Bhakri with Thecha": ["Thecha", "Bhakri thecha", "Jowar bhakri"],
    "Masale Bhaat": ["Masale bhat", "Masala bhat"],
    "Kombdi Vade": ["Kombdi vade", "Malvani chicken vade", "Malvani chicken"],
    "Tambda Pandhra Rassa Thali": ["Tambda rassa", "Pandhra rassa", "Kolhapuri thali"],
    "Sabudana Vada": ["Sabudana vada", "Sabudana wada"],
    "Maharashtrian Veg Thali": ["Maharashtrian thali", "Marathi thali", "Vegetarian thali"],
    "Hara Bhara Kabab": ["Hara bhara kabab", "Spinach kebab"],
    "Veg Manchurian Dry": ["Vegetable manchurian", "Veg manchurian"],
    "Crispy Corn": ["Crispy corn", "Fried sweet corn"],
    "Chilli Paneer Dry": ["Chilli paneer"],
    "Mushroom Tikka": ["Mushroom tikka", "Tandoori mushroom"],
    "Tandoori Aloo": ["Tandoori aloo", "Tandoori potato"],
    "Veg Spring Roll": ["Vegetable spring rolls", "Spring rolls"],
    "Dahi Kabab": ["Dahi kebab", "Dahi ke kabab"],
    "Corn Cheese Balls": ["Cheese corn balls", "Cheese balls fried"],
    "Paneer Malai Tikka": ["Malai paneer tikka", "Paneer tikka"],
    "Veg Seekh Kabab": ["Veg seekh kebab", "Vegetable seekh kabab"],
    "Kanda Bhaji": ["Kanda bhaji", "Onion bhaji", "Onion pakoda"],
    "Mirchi Bhaji": ["Mirchi bhaji", "Mirchi bajji", "Mirapakaya bajji"],
    "Achari Paneer Tikka": ["Achari paneer tikka", "Paneer tikka skewer"],
    "Tandoori Chicken (Half)": ["Tandoori chicken"],
    "Chilli Chicken Dry": ["Chilli chicken"],
    "Malai Chicken Tikka": ["Malai tikka", "Chicken malai tikka"],
    "Chicken Seekh Kabab": ["Chicken seekh kebab", "Seekh kebab"],
    "Reshmi Kabab": ["Reshmi kebab", "Chicken reshmi kabab"],
    "Chicken Sukka": ["Chicken sukka", "Chicken ghee roast"],
    "Afghani Chicken": ["Afghani chicken"],
    "Chicken Pakoda": ["Chicken pakora", "Chicken pakoda"],
    "Mutton Seekh Kabab": ["Mutton seekh kebab", "Seekh kabab lamb"],
    "Mutton Sukka": ["Mutton sukka", "Mutton chukka"],
    "Tangdi Kabab": ["Tangdi kabab", "Chicken drumstick tandoori"],
    "Egg Chilli": ["Egg chilli", "Chilli egg"],
    "Crispy Fried Chicken": ["Chicken tenders", "Fried chicken strips"],
    "Peri Peri Chicken Wings": ["Peri peri chicken wings", "Spicy chicken wings"],
    "Garlic Chicken Dry": ["Garlic chicken", "Dragon chicken"],
    "Pepper Chicken Dry": ["Pepper chicken", "Chicken pepper fry"],
    "Anda Fry": ["Egg roast kerala", "Egg masala fry", "Anda masala"],
    "Paneer Tikka Masala": ["Paneer tikka masala"],
    "Matar Paneer": ["Matar paneer", "Mattar paneer"],
    "Veg Kolhapuri": ["Veg kolhapuri", "Vegetable kolhapuri"],
    "Mix Veg": ["Mixed vegetable curry", "Mix veg sabzi"],
    "Bhindi Masala": ["Bhindi masala", "Okra curry"],
    "Methi Malai Matar": ["Methi malai matar", "Methi matar malai"],
    "Veg Handi": ["Veg handi", "Vegetable handi"],
    "Mushroom Masala": ["Mushroom masala", "Mushroom curry"],
    "Kaju Masala": ["Kaju curry", "Kaju masala", "Cashew curry"],
    "Chicken Kolhapuri": ["Chicken kolhapuri", "Kolhapuri chicken"],
    "Malvani Chicken": ["Malvani chicken", "Chicken malvani"],
    "Chicken Handi": ["Chicken handi"],
    "Gharguti Chicken Curry": ["Chicken curry"],
    "Chicken Masala": ["Chicken masala"],
    "Chicken Saoji": ["Saoji chicken", "Saoji"],
    "Chicken Rara": ["Chicken rara"],
    "Chicken Lababdar": ["Chicken lababdar"],
    "Methi Chicken": ["Methi chicken", "Murgh methi"],
    "Palak Chicken": ["Palak chicken", "Chicken saag"],
    "Chicken Kheema Masala": ["Chicken keema", "Chicken kheema"],
    "Hyderabadi Chicken Curry": ["Hyderabadi chicken curry", "Hyderabadi chicken"],
    "Afghani Chicken Curry": ["Chicken white gravy", "Chicken afghani curry"],
    "Chicken Mughlai": ["Mughlai chicken", "Chicken mughlai"],
    "Kolhapuri Mutton": ["Kolhapuri mutton", "Mutton kolhapuri"],
    "Mutton Saoji": ["Saoji mutton", "Mutton saoji"],
    "Malvani Mutton": ["Malvani mutton", "Mutton malvani"],
    "Mutton Tambda Rassa": ["Tambda rassa", "Mutton rassa"],
    "Mutton Kheema": ["Mutton keema", "Keema"],
    "Kheema Pav": ["Keema pav", "Kheema pav"],
    "Gharguti Mutton Curry": ["Mutton curry"],
    "Mutton Paya Soup": ["Paya soup", "Paya"],
    "Mutton Nalli Nihari": ["Nalli nihari", "Nihari"],
    "Mutton Pepper Masala": ["Mutton pepper fry", "Mutton pepper"],
    "Mutton Dalcha": ["Dalcha"],
    "Mutton Chaap Masala": ["Mutton chaap", "Lamb chops curry"],
    "Bombil Fry": ["Bombil fry", "Bombay duck fry", "Bombay duck"],
    "Prawns Koliwada": ["Prawn koliwada", "Prawns koliwada", "Fried prawns"],
    "Prawns Masala": ["Prawn masala", "Prawns curry"],
    "Malvani Fish Curry": ["Malvani fish curry", "Konkan fish curry"],
    "Malvani Fish Thali": ["Fish thali", "Malvani thali"],
    "Tisrya Masala": ["Tisrya", "Clam curry", "Clams masala"],
    "Rawas Tikka": ["Rawas", "Indian salmon fry", "Fish tikka"],
    "Fish Koliwada": ["Fish koliwada", "Fish fry koliwada"],
    "Bangda Fry": ["Bangda fry", "Mackerel fry"],
    "Prawns Rava Fry": ["Prawns rava fry", "Prawn rava fry", "Prawn fry"],
    "Surmai Curry": ["Surmai curry", "Kingfish curry"],
    "Pomfret Hirwa Masala": ["Green masala pomfret", "Pomfret green masala", "Pomfret"],
    "Butter Garlic Prawns": ["Butter garlic prawns", "Garlic shrimp"],
    "Prawns Sukka": ["Prawns sukka", "Prawn sukka", "Prawns roast"],
    "Chicken Dum Biryani": ["Chicken biryani"],
    "Mutton Dum Biryani": ["Mutton biryani"],
    "Veg Dum Biryani": ["Vegetable biryani", "Veg biryani"],
    "Prawns Biryani": ["Prawn biryani", "Prawns biryani"],
    "Hyderabadi Chicken Biryani": ["Hyderabadi biryani"],
    "Chicken Tikka Biryani": ["Chicken tikka biryani"],
    "Shetkari Special Chicken Biryani": ["Biryani with egg", "Chicken biryani egg"],
    "Mutton Kheema Biryani": ["Keema biryani", "Kheema biryani"],
    "Steamed Rice": ["Steamed basmati rice", "Steamed rice"],
    "Veg Pulao": ["Vegetable pulao", "Veg pulao"],
    "Peas Pulao": ["Peas pulao", "Matar pulao"],
    "Dal Khichdi": ["Dal khichdi", "Khichdi"],
    "Veg Fried Rice": ["Vegetable fried rice"],
    "Butter Tandoori Roti": ["Tandoori roti", "Roti butter"],
    "Plain Naan": ["Naan bread", "Naan"],
    "Garlic Naan": ["Garlic naan"],
    "Masala Kulcha": ["Kulcha", "Amritsari kulcha"],
    "Missi Roti": ["Missi roti"],
    "Jowar Bhakri": ["Jowar bhakri", "Bhakri"],
    "Bajra Bhakri": ["Bajra bhakri", "Bajra roti"],
    "Ghadichi Poli": ["Chapati", "Poli"],
    "Phulka": ["Phulka", "Roti"],
    "Pudina Paratha": ["Pudina paratha", "Mint paratha"],
    "Kashmiri Naan": ["Kashmiri naan", "Peshwari naan"],
    "Roti Basket": ["Bread basket indian", "Naan roti basket"],
    "Puri (2 pcs)": ["Puri bread", "Poori"],
    "Samosa (2 pcs)": ["Samosa"],
    "Samosa Pav": ["Samosa pav"],
    "Cheese Pav Bhaji": ["Cheese pav bhaji", "Pav bhaji"],
    "Ragda Pattice": ["Ragda pattice", "Ragda patties"],
    "Veg Sandwich": ["Bombay sandwich", "Vegetable sandwich"],
    "Cheese Grilled Sandwich": ["Grilled cheese sandwich"],
    "Veg Burger": ["Veggie burger"],
    "Veg Frankie": ["Frankie roll", "Kathi roll"],
    "Chicken Frankie": ["Chicken kathi roll", "Chicken roll"],
    "Veg Hakka Noodles": ["Hakka noodles", "Vegetable noodles"],
    "Chicken Hakka Noodles": ["Chicken noodles", "Chicken chow mein"],
    "Veg Momos": ["Momos", "Momo dumplings"],
    "Cutting Chai": ["Cutting chai", "Chai glass"],
    "Filter Coffee": ["Filter coffee", "Indian filter coffee"],
    "Masala Taak": ["Chaas", "Buttermilk"],
    "Sweet Lassi": ["Lassi"],
    "Kokum Sharbat": ["Kokum sharbat", "Kokum juice", "Kokum"],
    "Fresh Lime Water": ["Nimbu pani", "Lemonade glass"],
    "Watermelon Juice": ["Watermelon juice"],
    "Mosambi Juice": ["Sweet lime juice", "Mosambi juice"],
    "Piyush": ["Piyush drink", "Shrikhand"],
    "Kesar Masala Doodh": ["Masala milk", "Kesar milk", "Badam milk"],
    "Mineral Water (1 L)": ["Bottled water", "Water bottle"],
    "Soft Drink (300 ml)": ["Cola glass", "Soft drink glass"],
    "Gulab Jamun (2 pcs)": ["Gulab jamun"],
    "Amrakhand": ["Amrakhand", "Mango shrikhand"],
    "Ukadiche Modak (2 pcs)": ["Ukadiche modak", "Modak"],
    "Rasmalai (2 pcs)": ["Rasmalai"],
    "Gajar Halwa": ["Gajar ka halwa", "Carrot halwa"],
    "Jalebi with Rabdi": ["Jalebi rabri", "Jalebi rabdi"],
    "Malai Kulfi": ["Kulfi"],
    "Pista Kulfi": ["Pista kulfi", "Kulfi pistachio"],
    "Royal Falooda": ["Falooda"],
    "Brownie with Ice Cream": ["Brownie ice cream"],
    "Rava Sheera": ["Sheera", "Suji halwa", "Rava kesari"],
    "Kaju Katli (4 pcs)": ["Kaju katli", "Kaju barfi"],
}

# Fallbacks by keyword in the dish name (first match wins), then by category.
KEYWORD_FALLBACK = [
    ("biryani", "Biryani"), ("pulao", "Pulao"), ("fried rice", "Fried rice"),
    ("prawn", "Prawn curry"), ("pomfret", "Pomfret fry"), ("surmai", "Kingfish fry"),
    ("fish", "Fish curry india"), ("crab", "Crab curry"),
    ("mutton", "Mutton curry"), ("kheema", "Keema"), ("chicken", "Chicken curry india"),
    ("paneer", "Paneer curry"), ("kabab", "Kebab india"), ("tikka", "Tikka"),
    ("dal", "Dal india"), ("naan", "Naan"), ("roti", "Roti"), ("paratha", "Paratha"),
    ("bhakri", "Bhakri"), ("lassi", "Lassi"), ("juice", "Fruit juice glass"),
    ("chai", "Masala chai"), ("kulfi", "Kulfi"), ("halwa", "Halwa"),
]
CATEGORY_FALLBACK = {
    "Maharashtrian Dishes": "Maharashtrian cuisine",
    "Vegetarian Starters": "Indian vegetarian snack",
    "Non-Vegetarian Starters": "Chicken kebab",
    "Vegetarian Main Course": "Indian vegetable curry",
    "Chicken Main Course": "Chicken curry india",
    "Mutton Main Course": "Mutton curry",
    "Fish and Seafood": "Fish curry india",
    "Biryani and Rice": "Biryani",
    "Roti and Breads": "Indian bread",
    "Snacks and Fast Food": "Indian street food",
    "Beverages": "Indian drink glass",
    "Desserts": "Indian sweets",
}


def queries_for(dish):
    name = dish["name"]
    for q in DISH_QUERIES.get(name, [name]):
        yield "dish", q
    lowered = name.lower()
    for key, q in KEYWORD_FALLBACK:
        if key in lowered:
            yield "representative", q
            break
    yield "representative", CATEGORY_FALLBACK.get(dish["category"], "Indian food")

# Second pass after a visual check of the first download: better terms for
# dishes whose first photo was wrong (they are refetched with --reject).
DISH_QUERIES.update({
    "Bharli Vangi": ["Bharli vangi", "Stuffed brinjal", "Bharwa baingan", "Brinjal curry"],
    "Shev Bhaji": ["Sev bhaji", "Shev bhaji", "Sev tamatar", "Sev usal"],
    "Jowar Bhakri with Thecha": ["Thecha", "Bhakri", "Jowar roti"],
    "Crispy Corn": ["Crispy corn", "Corn fritters", "Fried corn"],
    "Chilli Paneer Dry": ["Chilli paneer", "Paneer chilli"],
    "Mushroom Tikka": ["Mushroom tikka", "Tandoori mushroom", "Mushroom skewer"],
    "Veg Spring Roll": ["Vegetable spring roll", "Spring roll"],
    "Honey Chilli Potato": ["Honey chilli potato", "Chilli potato", "Potato wedges spicy"],
    "Mirchi Bhaji": ["Mirchi bajji", "Mirchi bhaji", "Chilli bhaji", "Mirchi vada"],
    "Chilli Mushroom": ["Chilli mushroom", "Mushroom manchurian", "Mushroom stir fry"],
    "Paneer Tikka": ["Paneer tikka skewer", "Paneer tikka"],
    "Afghani Chicken": ["Afghani chicken", "Chicken malai kebab", "Chicken kebab cream"],
    "Egg Chilli": ["Chilli egg", "Egg manchurian", "Egg fry"],
    "Paneer Tikka Masala": ["Paneer tikka masala", "Paneer masala"],
    "Matar Paneer": ["Matar paneer", "Mutter paneer", "Peas paneer"],
    "Veg Handi": ["Vegetable handi", "Mixed vegetable curry", "Vegetable kurma"],
    "Chicken Saoji": ["Saoji chicken", "Saoji", "Spicy chicken curry"],
    "Chicken Rara": ["Chicken rara", "Rara chicken", "Chicken keema curry"],
    "Palak Chicken": ["Palak chicken", "Saag chicken", "Chicken saag", "Spinach chicken curry"],
    "Chicken Kheema Masala": ["Chicken keema", "Chicken mince curry", "Keema matar"],
    "Kolhapuri Mutton": ["Kolhapuri mutton", "Mutton kolhapuri", "Mutton thali"],
    "Mutton Kheema": ["Mutton keema", "Keema curry", "Kheema", "Keema matar"],
    "Mutton Paya Soup": ["Paya soup", "Paya curry", "Trotter soup", "Paya"],
    "Surmai Fry": ["Surmai fry", "Kingfish fry", "Fish fry rava", "Fried fish steak"],
    "Malvani Fish Curry": ["Malvani fish curry", "Konkani fish curry", "Fish curry coconut"],
    "Tisrya Masala": ["Tisrya", "Clam masala", "Clams curry", "Clam curry"],
    "Rawas Tikka": ["Rawas fry", "Salmon tikka", "Fish tikka", "Tandoori fish"],
    "Steamed Rice": ["Steamed rice bowl", "White rice bowl", "Plain rice", "Steamed rice"],
    "Dal Khichdi": ["Dal khichdi", "Moong dal khichdi", "Khichri", "Khichdi"],
    "Plain Naan": ["Plain naan", "Naan bread", "Naan"],
    "Laccha Paratha": ["Lachha paratha", "Laccha paratha", "Paratha"],
    "Masala Kulcha": ["Kulcha", "Amritsari kulcha", "Stuffed kulcha"],
    "Phulka": ["Phulka", "Chapati", "Roti"],
    "Roti Basket": ["Naan basket", "Assorted naan", "Bread basket naan", "Naan"],
    "Samosa (2 pcs)": ["Samosa plate", "Samosas", "Samosa"],
    "Veg Sandwich": ["Bombay sandwich", "Vegetable sandwich", "Veg sandwich"],
    "Cheese Grilled Sandwich": ["Grilled cheese sandwich", "Cheese toast sandwich", "Grilled sandwich"],
    "Veg Burger": ["Veggie burger", "Vegetable burger", "Veg burger", "Aloo tikki burger"],
    "Veg Hakka Noodles": ["Hakka noodles", "Vegetable noodles", "Vegetable chow mein"],
    "Veg Momos": ["Veg momos", "Momo dumplings", "Momos", "Steamed dumplings"],
    "Jeera Rice": ["Jeera rice", "Cumin rice"],
    "Bhel Puri": ["Bhel puri", "Bhelpuri", "Bhel"],
    "Sol Kadhi": ["Sol kadhi", "Solkadhi", "Kokum drink", "Kokum"],
})
DISH_QUERIES.update({
    "Cold Coffee": ["Cold coffee glass", "Iced coffee milkshake", "Cold coffee"],
    "Masala Taak": ["Chaas", "Masala chaas", "Buttermilk drink", "Lassi"],
    "Mango Lassi": ["Mango lassi", "Mango shake", "Mango smoothie"],
    "Jaljeera": ["Jaljeera", "Jal jeera", "Cumin drink", "Lemonade mint"],
    "Mosambi Juice": ["Mosambi juice", "Sweet lime juice", "Orange juice glass"],
    "Mineral Water (1 L)": ["Glass of water", "Drinking water glass", "Water glass"],
    "Soft Drink (300 ml)": ["Cola glass ice", "Glass of cola", "Soda glass ice"],
    "Gulab Jamun (2 pcs)": ["Gulab jamun dessert", "Gulab jamun bowl", "Gulaab jamun"],
    "Shrikhand": ["Shrikhand", "Shrikhand bowl", "Saffron yogurt dessert"],
    "Jalebi": ["Jalebi sweet", "Jalebis", "Jilebi"],
})
DISH_QUERIES.update({
    "Crispy Corn": ["Corn fritter", "Crispy corn"],
    "Mushroom Tikka": ["Tandoori mushroom", "Grilled mushroom skewer"],
    "Chilli Mushroom": ["Chilli mushroom", "Stir fried mushrooms"],
    "Paneer Tikka Masala": ["Paneer tikka masala", "Shahi paneer", "Paneer makhani"],
    "Veg Handi": ["Navratan korma", "Vegetable korma", "Mixed vegetable curry"],
    "Steamed Rice": ["Cooked rice", "Steamed rice"],
    "Dal Khichdi": ["Khichdi", "Khichri"],
    "Phulka": ["Phulka", "Chapati"],
    "Samosa (2 pcs)": ["Samosa", "Samosas"],
    "Veg Hakka Noodles": ["Hakka noodles", "Chow mein"],
    "Masala Taak": ["Chaas", "Buttermilk", "Spiced buttermilk"],
    "Mango Lassi": ["Mango lassi", "Mango milkshake"],
    "Soft Drink (300 ml)": ["Soft drink glass ice", "Glass of soda with ice", "Lemonade glass ice"],
    "Shrikhand": ["Shrikhand", "Amrakhand", "Sweet strained yogurt"],
    "Egg Chilli": ["Egg curry", "Anda curry", "Egg masala"],
})
