"""
Royal Shetkari sample menu: 12 categories x 20 dishes = 240 dishes.

SAMPLE DATA FOR OWNER REVIEW. Prices are realistic Pune/Maharashtra
restaurant prices in INR picked for the demo, not the restaurant's real
price list. GST is set to 5% on every dish (the usual rate for restaurant
service without input tax credit), but an outlet only collects GST once a
valid GSTIN is saved in Outlet Settings (tenants/models.py), and the seed
deliberately saves no GSTIN: no business registration is invented here.

Each dish: (name, description, price_inr, is_veg, prep_minutes, station_key)
station_key None means the category's default station.
"""

# Kitchen stations: key -> display name
STATIONS = {
    "main": "Main Kitchen (Curries)",
    "tandoor": "Tandoor",
    "snacks": "Snacks & Chaat Counter",
    "biryani": "Biryani & Rice Handi",
    "bar": "Beverage Counter",
    "dessert": "Dessert Counter",
}
DEFAULT_STATION = "main"

# (category name, default station key, dishes)
MENU = [
    ("Maharashtrian Dishes", "main", [
        ("Puneri Misal Pav", "Sprouted moth-bean usal in a spicy kat rassa, topped with farsan, onion and coriander, served with two pav and lemon.", 140, True, 12, None),
        ("Kolhapuri Misal Pav", "Fiery Kolhapuri-style misal with extra tarri, crunchy farsan and soft pav.", 160, True, 12, None),
        ("Pithla Bhakri", "Comforting gram-flour pithla tempered with garlic and green chilli, with a hot jowar bhakri and thecha.", 150, True, 15, None),
        ("Zunka Bhakar", "Dry besan zunka with onions and spices, served with bajra bhakri and raw onion.", 150, True, 15, None),
        ("Bharli Vangi", "Baby brinjals stuffed with roasted peanut, coconut and goda masala, slow-cooked in gravy.", 190, True, 20, None),
        ("Thalipeeth", "Crisp multigrain bhajani flatbread with onion and coriander, served with white butter and curd.", 130, True, 15, "tandoor"),
        ("Sabudana Khichdi", "Soft sago pearls tossed with roasted peanuts, potato, cumin and green chilli.", 120, True, 10, None),
        ("Kanda Poha", "Flattened rice with onion, turmeric, peanuts and curry leaves, finished with lemon and sev.", 90, True, 8, "snacks"),
        ("Kothimbir Vadi", "Steamed and shallow-fried coriander and gram-flour squares with green chutney.", 120, True, 12, "snacks"),
        ("Alu Vadi", "Colocasia leaves rolled with spiced gram-flour paste, steamed, sliced and crisp-fried.", 130, True, 12, "snacks"),
        ("Shev Bhaji", "Spicy Khandeshi-style onion-tomato gravy topped with thick shev, with chapati or bhakri.", 170, True, 15, None),
        ("Matki Usal", "Sprouted moth beans cooked with goda masala and coconut, garnished with coriander.", 150, True, 15, None),
        ("Puran Poli", "Sweet flatbread stuffed with chana dal and jaggery puran, served with ghee and katachi amti.", 120, True, 10, "tandoor"),
        ("Varan Bhaat", "Plain tur dal varan over steamed rice with a spoon of ghee and lemon.", 140, True, 8, None),
        ("Jowar Bhakri with Thecha", "Hand-patted jowar bhakri with green-chilli and peanut thecha and raw onion.", 110, True, 10, "tandoor"),
        ("Masale Bhaat", "Maharashtrian spiced rice with tondli, goda masala and cashew, topped with fresh coconut.", 180, True, 18, "biryani"),
        ("Kombdi Vade", "Malvani chicken curry with fluffy fried rice-flour vade and sol kadhi.", 320, False, 25, None),
        ("Tambda Pandhra Rassa Thali", "Kolhapuri mutton thali with sukka, tambda and pandhra rassa, bhakri, rice and onion-lemon.", 380, False, 25, None),
        ("Sabudana Vada", "Crisp sago and peanut fritters with sweet curd and green chutney.", 110, True, 12, "snacks"),
        ("Maharashtrian Veg Thali", "Two seasonal bhajis, varan, amti, chapati, bhakri, rice, koshimbir, papad and a sweet.", 260, True, 15, None),
    ]),
    ("Vegetarian Starters", "tandoor", [
        ("Paneer Tikka", "Cottage cheese cubes marinated in hung curd and spices, char-grilled with peppers and onion.", 260, True, 18, None),
        ("Hara Bhara Kabab", "Spinach, green pea and potato patties with a crisp crust and mint chutney.", 210, True, 15, "snacks"),
        ("Veg Manchurian Dry", "Fried mixed-vegetable dumplings tossed in a soy, garlic and spring-onion glaze.", 200, True, 15, "snacks"),
        ("Gobi Manchurian", "Crisp cauliflower florets tossed in an Indo-Chinese chilli garlic sauce.", 200, True, 15, "snacks"),
        ("Crispy Corn", "Golden fried sweet corn tossed with onion, capsicum, pepper and chaat masala.", 210, True, 12, "snacks"),
        ("Chilli Paneer Dry", "Paneer cubes wok-tossed with green chillies, capsicum, onion and soy.", 250, True, 15, "snacks"),
        ("Paneer Pakoda", "Paneer slices stuffed with green chutney, dipped in spiced gram batter and fried.", 190, True, 12, "snacks"),
        ("Mushroom Tikka", "Button mushrooms in a tandoori marinade, roasted in the clay oven.", 240, True, 18, None),
        ("Tandoori Aloo", "Scooped potatoes stuffed with paneer and dry fruit, roasted in the tandoor.", 210, True, 20, None),
        ("Veg Spring Roll", "Crisp rolls filled with stir-fried cabbage, carrot and noodles, with sweet chilli sauce.", 190, True, 12, "snacks"),
        ("Honey Chilli Potato", "Crispy potato fingers tossed in honey, chilli and sesame.", 200, True, 12, "snacks"),
        ("Dahi Kabab", "Melt-in-the-mouth hung-curd kababs with a crumb crust.", 230, True, 15, "snacks"),
        ("Corn Cheese Balls", "Sweet corn and cheese croquettes, golden fried, with tomato dip.", 220, True, 12, "snacks"),
        ("Paneer Malai Tikka", "Paneer in a creamy cashew, cheese and cardamom marinade, lightly charred.", 280, True, 18, None),
        ("Veg Seekh Kabab", "Minced vegetable and paneer seekh grilled on skewers, with onion rings.", 230, True, 18, None),
        ("Kanda Bhaji", "Crunchy onion fritters in gram-flour batter with fried green chillies.", 120, True, 10, "snacks"),
        ("Mirchi Bhaji", "Large green chillies stuffed with spiced potato, battered and fried.", 110, True, 10, "snacks"),
        ("Chilli Mushroom", "Mushrooms tossed with chilli, garlic, spring onion and soy.", 230, True, 15, "snacks"),
        ("Achari Paneer Tikka", "Paneer in a tangy pickle-spice marinade, grilled in the tandoor.", 270, True, 18, None),
        ("Masala Papad", "Roasted papad topped with onion, tomato, coriander and chaat masala.", 60, True, 5, "snacks"),
    ]),
    ("Non-Vegetarian Starters", "tandoor", [
        ("Chicken Tikka", "Boneless chicken marinated overnight in yoghurt and spices, roasted in the tandoor.", 300, False, 20, None),
        ("Tandoori Chicken (Half)", "Half chicken on the bone in classic red tandoori marinade, with mint chutney.", 320, False, 25, None),
        ("Chicken 65", "Spicy deep-fried chicken bites tempered with curry leaves and green chilli.", 280, False, 15, "snacks"),
        ("Chicken Lollipop", "Frenched chicken wings, fried crisp and served with Schezwan sauce.", 290, False, 18, "snacks"),
        ("Chilli Chicken Dry", "Fried chicken tossed with green chilli, capsicum, onion and soy.", 290, False, 15, "snacks"),
        ("Malai Chicken Tikka", "Chicken in a mild cream, cheese and cashew marinade, char-grilled.", 320, False, 20, None),
        ("Chicken Seekh Kabab", "Minced chicken with herbs and spices, grilled on skewers.", 300, False, 18, None),
        ("Reshmi Kabab", "Silky minced-chicken kabab with cream and white pepper.", 320, False, 18, None),
        ("Chicken Sukka", "Dry Kolhapuri chicken with coconut, onion and fiery masala.", 300, False, 20, "main"),
        ("Afghani Chicken", "Chicken in a creamy, mildly spiced marinade, slow-roasted.", 340, False, 25, None),
        ("Chicken Pakoda", "Boneless chicken fritters in spiced gram-flour batter.", 260, False, 15, "snacks"),
        ("Mutton Seekh Kabab", "Minced mutton with mint and spices, grilled on skewers.", 380, False, 20, None),
        ("Mutton Sukka", "Tender mutton pieces dry-roasted with coconut and Kolhapuri masala.", 380, False, 25, "main"),
        ("Tangdi Kabab", "Chicken drumsticks in a rich tandoori marinade.", 330, False, 25, None),
        ("Egg Chilli", "Boiled egg quarters, battered, fried and tossed in chilli sauce.", 180, False, 12, "snacks"),
        ("Crispy Fried Chicken", "Crumb-coated chicken strips, fried golden, with garlic mayo.", 280, False, 15, "snacks"),
        ("Peri Peri Chicken Wings", "Chicken wings tossed in a hot peri-peri spice mix.", 290, False, 18, "snacks"),
        ("Garlic Chicken Dry", "Fried chicken tossed with burnt garlic and spring onion.", 290, False, 15, "snacks"),
        ("Pepper Chicken Dry", "Chicken roasted with crushed black pepper and curry leaves.", 300, False, 18, "main"),
        ("Anda Fry", "Boiled eggs pan-fried with onion, tomato and Malvani masala.", 160, False, 10, "main"),
    ]),
    ("Vegetarian Main Course", "main", [
        ("Paneer Butter Masala", "Paneer in a smooth, buttery tomato and cashew gravy.", 260, True, 15, None),
        ("Kadai Paneer", "Paneer with capsicum and onion in a kadai-roasted spice gravy.", 260, True, 15, None),
        ("Palak Paneer", "Paneer in a smooth spinach gravy tempered with garlic.", 250, True, 15, None),
        ("Shahi Paneer", "Paneer in a rich, mildly sweet cashew and cream gravy.", 270, True, 15, None),
        ("Paneer Tikka Masala", "Tandoor-grilled paneer tikka simmered in a spicy masala gravy.", 280, True, 18, None),
        ("Matar Paneer", "Paneer and green peas in a home-style onion-tomato gravy.", 240, True, 15, None),
        ("Malai Kofta", "Paneer and potato koftas in a creamy cashew gravy.", 260, True, 18, None),
        ("Dal Makhani", "Whole black urad dal slow-cooked overnight with butter and cream.", 220, True, 12, None),
        ("Dal Tadka", "Yellow dal tempered with ghee, cumin, garlic and red chilli.", 180, True, 10, None),
        ("Chana Masala", "Chickpeas in a tangy, spiced onion-tomato gravy.", 200, True, 12, None),
        ("Veg Kolhapuri", "Mixed vegetables in a fiery Kolhapuri coconut and chilli masala.", 230, True, 15, None),
        ("Mix Veg", "Seasonal vegetables cooked in a mildly spiced gravy.", 210, True, 15, None),
        ("Aloo Gobi", "Potato and cauliflower dry-cooked with cumin and turmeric.", 190, True, 15, None),
        ("Bhindi Masala", "Okra stir-fried with onion, tomato and dry spices.", 200, True, 15, None),
        ("Baingan Bharta", "Fire-roasted brinjal mashed and cooked with onion, tomato and garlic.", 200, True, 15, None),
        ("Methi Malai Matar", "Green peas and fenugreek leaves in a creamy white gravy.", 240, True, 15, None),
        ("Veg Handi", "Assorted vegetables slow-cooked in a clay handi with whole spices.", 230, True, 18, None),
        ("Paneer Bhurji", "Scrambled paneer with onion, tomato, green chilli and coriander.", 260, True, 12, None),
        ("Mushroom Masala", "Button mushrooms in a spicy onion-tomato masala.", 240, True, 15, None),
        ("Kaju Masala", "Roasted cashews in a rich, mildly spiced tomato gravy.", 290, True, 15, None),
    ]),
    ("Chicken Main Course", "main", [
        ("Butter Chicken", "Tandoori chicken in a velvety tomato, butter and cream gravy.", 340, False, 18, None),
        ("Chicken Tikka Masala", "Chicken tikka simmered in a spicy onion-tomato masala.", 340, False, 18, None),
        ("Kadai Chicken", "Chicken with capsicum and onion in kadai-roasted spices.", 320, False, 18, None),
        ("Chicken Kolhapuri", "Chicken in the famous fiery Kolhapuri masala with tambda rassa.", 330, False, 20, None),
        ("Malvani Chicken", "Coastal Malvani chicken curry with roasted coconut and Malvani masala.", 330, False, 20, None),
        ("Chicken Handi", "Chicken slow-cooked in a clay handi with whole spices and cream.", 340, False, 20, None),
        ("Gharguti Chicken Curry", "Home-style Maharashtrian chicken curry with goda masala.", 300, False, 20, None),
        ("Chicken Masala", "Chicken in a thick, aromatic onion-tomato masala.", 310, False, 18, None),
        ("Chicken Do Pyaza", "Chicken cooked with double the onions, sweet and spicy.", 320, False, 18, None),
        ("Chicken Korma", "Chicken in a mild, nutty yoghurt and cashew gravy.", 340, False, 20, None),
        ("Chicken Saoji", "Nagpur-style Saoji chicken in a dark, spicy masala.", 330, False, 20, None),
        ("Chicken Rara", "Chicken pieces and chicken mince cooked together in a rich gravy.", 360, False, 22, None),
        ("Chicken Lababdar", "Chicken in a creamy, tangy tomato gravy with onion and capsicum.", 350, False, 18, None),
        ("Methi Chicken", "Chicken cooked with fresh fenugreek leaves.", 330, False, 18, None),
        ("Palak Chicken", "Chicken in a garlicky spinach gravy.", 320, False, 18, None),
        ("Chicken Kheema Masala", "Minced chicken cooked with green peas and spices.", 320, False, 15, None),
        ("Hyderabadi Chicken Curry", "Chicken in a tangy, peppery Hyderabadi-style gravy.", 330, False, 20, None),
        ("Chicken Chettinad", "Chicken in a peppery South Indian Chettinad masala.", 340, False, 20, None),
        ("Afghani Chicken Curry", "Chicken in a creamy, mildly spiced white gravy.", 360, False, 20, None),
        ("Chicken Mughlai", "Chicken in a rich Mughlai gravy with egg and dry fruits.", 350, False, 20, None),
    ]),
    ("Mutton Main Course", "main", [
        ("Mutton Rogan Josh", "Kashmiri-style mutton in a fragrant red gravy.", 420, False, 25, None),
        ("Kolhapuri Mutton", "Mutton in the signature fiery Kolhapuri masala.", 420, False, 25, None),
        ("Mutton Saoji", "Nagpur-style mutton in a dark, spicy Saoji masala.", 420, False, 25, None),
        ("Malvani Mutton", "Coastal mutton curry with roasted coconut and Malvani masala.", 420, False, 25, None),
        ("Mutton Tambda Rassa", "Mutton in the red Kolhapuri tambda rassa.", 400, False, 25, None),
        ("Mutton Handi", "Mutton slow-cooked in a sealed clay handi.", 430, False, 28, None),
        ("Mutton Kadai", "Mutton with capsicum and onion in kadai-roasted spices.", 420, False, 25, None),
        ("Mutton Kheema", "Minced mutton cooked with peas and spices.", 380, False, 18, None),
        ("Kheema Pav", "Spicy mutton kheema served with buttered pav.", 260, False, 15, None),
        ("Mutton Masala", "Mutton in a thick, aromatic onion-tomato masala.", 410, False, 25, None),
        ("Mutton Do Pyaza", "Mutton cooked with plenty of onions.", 420, False, 25, None),
        ("Mutton Korma", "Mutton in a rich, nutty yoghurt gravy.", 440, False, 28, None),
        ("Mutton Bhuna", "Mutton roasted slowly with spices until dry and dark.", 430, False, 28, None),
        ("Mutton Paya Soup", "Slow-cooked trotter soup with pepper and spices.", 250, False, 15, None),
        ("Mutton Nalli Nihari", "Slow-cooked shank in a silky nihari gravy.", 480, False, 30, None),
        ("Mutton Pepper Masala", "Mutton in a peppery, dry masala with curry leaves.", 430, False, 25, None),
        ("Gharguti Mutton Curry", "Home-style Maharashtrian mutton curry with goda masala.", 400, False, 25, None),
        ("Mutton Dalcha", "Mutton cooked with chana dal and tamarind, Hyderabadi style.", 410, False, 25, None),
        ("Laal Maas", "Rajasthani mutton in a fiery red-chilli gravy.", 450, False, 28, None),
        ("Mutton Chaap Masala", "Mutton chops in a rich masala gravy.", 480, False, 28, None),
    ]),
    ("Fish and Seafood", "main", [
        ("Surmai Fry", "Kingfish steak in Malvani masala and rava, pan-fried crisp.", 420, False, 18, None),
        ("Pomfret Fry", "Whole pomfret in red masala, rava-coated and fried.", 480, False, 20, None),
        ("Bombil Fry", "Bombay duck butterflied, rava-crusted and fried crisp.", 300, False, 15, None),
        ("Prawns Koliwada", "Prawns in a spicy Koliwada batter, deep-fried.", 380, False, 15, "snacks"),
        ("Prawns Masala", "Prawns in a thick onion-tomato and coconut masala.", 400, False, 18, None),
        ("Malvani Fish Curry", "Fish in a tangy coconut and kokum Malvani curry.", 380, False, 18, None),
        ("Malvani Fish Thali", "Fish fry, fish curry, sol kadhi, rice, chapati and bhakri.", 450, False, 22, None),
        ("Crab Masala", "Whole crab cooked in a spicy coastal masala.", 520, False, 25, None),
        ("Tisrya Masala", "Clams cooked with coconut and Malvani spices.", 340, False, 18, None),
        ("Rawas Tikka", "Indian salmon cubes in tandoori marinade, roasted.", 450, False, 18, "tandoor"),
        ("Fish Koliwada", "Fish strips in spicy Koliwada batter, deep-fried.", 360, False, 15, "snacks"),
        ("Goan Fish Curry", "Fish in a tangy Goan coconut and red-chilli curry.", 380, False, 18, None),
        ("Bangda Fry", "Whole mackerel stuffed with red masala and pan-fried.", 260, False, 15, None),
        ("Prawns Rava Fry", "Prawns coated in masala and semolina, pan-fried.", 400, False, 15, None),
        ("Surmai Curry", "Kingfish in a coconut-based Konkan curry.", 420, False, 18, None),
        ("Pomfret Hirwa Masala", "Pomfret in a green coriander, mint and coconut masala.", 520, False, 22, None),
        ("Chilli Fish", "Fried fish tossed with chilli, garlic and capsicum.", 360, False, 15, "snacks"),
        ("Butter Garlic Prawns", "Prawns sauteed in butter, garlic and parsley.", 450, False, 15, None),
        ("Fish Tikka", "Boneless fish in a tandoori marinade, roasted.", 400, False, 18, "tandoor"),
        ("Prawns Sukka", "Prawns dry-roasted with coconut and spices.", 420, False, 18, None),
    ]),
    ("Biryani and Rice", "biryani", [
        ("Chicken Dum Biryani", "Basmati rice and marinated chicken layered and slow-cooked on dum, with raita.", 320, False, 25, None),
        ("Mutton Dum Biryani", "Basmati rice and tender mutton slow-cooked on dum, with raita.", 400, False, 30, None),
        ("Veg Dum Biryani", "Basmati rice with mixed vegetables and saffron, cooked on dum.", 250, True, 20, None),
        ("Paneer Biryani", "Basmati rice layered with spiced paneer and fried onions.", 280, True, 20, None),
        ("Egg Biryani", "Fragrant biryani rice with masala boiled eggs.", 240, False, 18, None),
        ("Prawns Biryani", "Basmati rice layered with coastal-spiced prawns.", 420, False, 25, None),
        ("Hyderabadi Chicken Biryani", "Kacchi-style Hyderabadi biryani with saffron and mint.", 340, False, 28, None),
        ("Chicken Tikka Biryani", "Smoky chicken tikka layered with biryani rice.", 350, False, 25, None),
        ("Shetkari Special Chicken Biryani", "House-special spicy biryani with Kolhapuri masala and boiled egg.", 360, False, 25, None),
        ("Mutton Kheema Biryani", "Biryani rice layered with spiced mutton kheema.", 380, False, 25, None),
        ("Jeera Rice", "Basmati rice tempered with cumin and ghee.", 140, True, 8, None),
        ("Steamed Rice", "Plain steamed basmati rice.", 110, True, 5, None),
        ("Veg Pulao", "Basmati rice cooked with mixed vegetables and whole spices.", 190, True, 12, None),
        ("Peas Pulao", "Basmati rice with green peas and whole spices.", 180, True, 12, None),
        ("Kashmiri Pulao", "Mildly sweet pulao with dry fruits, fruit and saffron.", 220, True, 12, None),
        ("Curd Rice", "Rice mixed with curd and tempered with mustard and curry leaves.", 160, True, 8, None),
        ("Dal Khichdi", "Rice and moong dal khichdi with ghee and papad.", 180, True, 12, None),
        ("Veg Fried Rice", "Wok-tossed rice with vegetables and soy.", 200, True, 12, "snacks"),
        ("Chicken Fried Rice", "Wok-tossed rice with chicken, egg and spring onion.", 240, False, 12, "snacks"),
        ("Egg Fried Rice", "Wok-tossed rice with scrambled egg and spring onion.", 210, False, 12, "snacks"),
    ]),
    ("Roti and Breads", "tandoor", [
        ("Tandoori Roti", "Whole-wheat roti baked in the tandoor.", 30, True, 5, None),
        ("Butter Tandoori Roti", "Tandoori roti brushed with butter.", 35, True, 5, None),
        ("Plain Naan", "Soft leavened bread from the tandoor.", 45, True, 6, None),
        ("Butter Naan", "Naan brushed generously with butter.", 55, True, 6, None),
        ("Garlic Naan", "Naan topped with chopped garlic and coriander.", 70, True, 7, None),
        ("Cheese Naan", "Naan stuffed with molten cheese.", 110, True, 8, None),
        ("Laccha Paratha", "Flaky, layered whole-wheat paratha.", 60, True, 7, None),
        ("Aloo Paratha", "Paratha stuffed with spiced potato, with curd and pickle.", 110, True, 10, None),
        ("Paneer Paratha", "Paratha stuffed with spiced paneer, with curd and pickle.", 130, True, 10, None),
        ("Masala Kulcha", "Tandoori kulcha stuffed with spiced potato and onion.", 90, True, 8, None),
        ("Missi Roti", "Gram-flour and wheat roti with spices.", 50, True, 6, None),
        ("Rumali Roti", "Paper-thin handkerchief roti.", 45, True, 6, None),
        ("Jowar Bhakri", "Hand-patted sorghum flatbread.", 40, True, 7, None),
        ("Bajra Bhakri", "Hand-patted pearl-millet flatbread.", 40, True, 7, None),
        ("Ghadichi Poli", "Layered Maharashtrian chapati with ghee.", 25, True, 5, None),
        ("Phulka", "Soft puffed whole-wheat phulka.", 20, True, 4, None),
        ("Pudina Paratha", "Laccha paratha sprinkled with dried mint.", 65, True, 7, None),
        ("Kashmiri Naan", "Naan stuffed with dry fruits and cherries.", 120, True, 8, None),
        ("Roti Basket", "Assorted basket: two butter naan, two tandoori roti and one laccha paratha.", 180, True, 10, None),
        ("Puri (2 pcs)", "Two puffed deep-fried puris.", 50, True, 6, "main"),
    ]),
    ("Snacks and Fast Food", "snacks", [
        ("Vada Pav", "Spiced potato vada in a pav with dry garlic chutney and fried chilli.", 30, True, 5, None),
        ("Samosa (2 pcs)", "Crisp pastry stuffed with spiced potato and peas, with chutneys.", 40, True, 5, None),
        ("Samosa Pav", "Samosa tucked in pav with chutneys.", 40, True, 5, None),
        ("Pav Bhaji", "Buttery mashed-vegetable bhaji with two toasted pav, onion and lemon.", 150, True, 12, None),
        ("Cheese Pav Bhaji", "Pav bhaji topped with grated cheese.", 180, True, 12, None),
        ("Dabeli", "Kutchi dabeli: spiced potato in pav with peanuts, pomegranate and sev.", 50, True, 6, None),
        ("Bhel Puri", "Puffed rice with onion, tomato, chutneys and sev.", 70, True, 5, None),
        ("Sev Puri", "Crisp puris topped with potato, chutneys and sev.", 80, True, 6, None),
        ("Pani Puri", "Six puris with spiced potato and tangy mint water.", 60, True, 5, None),
        ("Ragda Pattice", "Potato patties with white-pea ragda and chutneys.", 100, True, 8, None),
        ("Veg Sandwich", "Bombay-style sandwich with vegetables and green chutney.", 90, True, 8, None),
        ("Cheese Grilled Sandwich", "Grilled sandwich with vegetables and cheese.", 140, True, 10, None),
        ("Veg Burger", "Crisp vegetable patty burger with lettuce and mayo.", 120, True, 10, None),
        ("Chicken Burger", "Crumbed chicken patty burger with lettuce and mayo.", 160, False, 12, None),
        ("French Fries", "Crisp salted potato fries.", 110, True, 8, None),
        ("Veg Frankie", "Wrap with spiced vegetable filling and onions.", 120, True, 8, None),
        ("Chicken Frankie", "Wrap with spiced chicken tikka filling and onions.", 150, False, 10, None),
        ("Veg Hakka Noodles", "Wok-tossed noodles with vegetables.", 180, True, 12, None),
        ("Chicken Hakka Noodles", "Wok-tossed noodles with chicken and vegetables.", 220, False, 12, None),
        ("Veg Momos", "Steamed dumplings with vegetable filling and red chutney.", 140, True, 12, None),
    ]),
    ("Beverages", "bar", [
        ("Masala Chai", "Tea brewed with milk, ginger and cardamom.", 30, True, 4, None),
        ("Cutting Chai", "Half glass of strong, sweet Mumbai-style chai.", 20, True, 3, None),
        ("Filter Coffee", "South Indian filter coffee with frothy milk.", 50, True, 4, None),
        ("Cold Coffee", "Chilled blended coffee with milk and ice cream.", 120, True, 5, None),
        ("Sol Kadhi", "Kokum and coconut-milk digestive with garlic and coriander.", 70, True, 3, None),
        ("Masala Taak", "Spiced buttermilk with ginger, chilli and coriander.", 50, True, 3, None),
        ("Sweet Lassi", "Thick sweet yoghurt drink.", 90, True, 4, None),
        ("Mango Lassi", "Yoghurt blended with Alphonso mango pulp.", 120, True, 4, None),
        ("Kokum Sharbat", "Refreshing sweet-sour kokum cooler.", 70, True, 3, None),
        ("Fresh Lime Soda", "Fresh lime with soda, sweet or salted.", 80, True, 3, None),
        ("Fresh Lime Water", "Fresh lime with chilled water, sweet or salted.", 60, True, 3, None),
        ("Jaljeera", "Tangy cumin and mint cooler.", 60, True, 3, None),
        ("Sugarcane Juice", "Freshly crushed sugarcane juice with lemon and ginger.", 60, True, 4, None),
        ("Watermelon Juice", "Fresh watermelon juice.", 90, True, 4, None),
        ("Mosambi Juice", "Fresh sweet-lime juice.", 100, True, 4, None),
        ("Piyush", "Shrikhand-based saffron and cardamom drink.", 110, True, 4, None),
        ("Kesar Masala Doodh", "Hot or cold saffron milk with dry fruits.", 90, True, 5, None),
        ("Mineral Water (1 L)", "Packaged drinking water, 1 litre.", 20, True, 1, None),
        ("Soft Drink (300 ml)", "Chilled aerated soft drink, 300 ml.", 40, True, 1, None),
        ("Aam Panna", "Raw-mango cooler with roasted cumin.", 80, True, 3, None),
    ]),
    ("Desserts", "dessert", [
        ("Gulab Jamun (2 pcs)", "Soft khoya dumplings in rose-cardamom syrup.", 80, True, 3, None),
        ("Shrikhand", "Strained yoghurt sweetened with sugar, saffron and cardamom.", 90, True, 3, None),
        ("Amrakhand", "Shrikhand blended with Alphonso mango pulp.", 110, True, 3, None),
        ("Basundi", "Slow-reduced sweetened milk with nuts and saffron.", 110, True, 3, None),
        ("Ukadiche Modak (2 pcs)", "Steamed rice-flour modak with coconut-jaggery filling and ghee.", 120, True, 10, None),
        ("Rasmalai (2 pcs)", "Chhena discs in saffron-cardamom milk.", 120, True, 3, None),
        ("Kheer", "Rice pudding with milk, cardamom and nuts.", 100, True, 3, None),
        ("Gajar Halwa", "Slow-cooked carrot halwa with khoya and nuts.", 120, True, 5, None),
        ("Moong Dal Halwa", "Rich moong dal halwa with ghee and nuts.", 140, True, 5, None),
        ("Jalebi", "Crisp, syrup-soaked jalebi.", 90, True, 5, None),
        ("Jalebi with Rabdi", "Hot jalebi with chilled rabdi.", 150, True, 5, None),
        ("Malai Kulfi", "Traditional creamy kulfi.", 90, True, 2, None),
        ("Pista Kulfi", "Kulfi with pistachios.", 100, True, 2, None),
        ("Royal Falooda", "Rose milk with vermicelli, sabja, jelly and ice cream.", 150, True, 5, None),
        ("Vanilla Ice Cream", "Two scoops of vanilla ice cream.", 80, True, 2, None),
        ("Brownie with Ice Cream", "Warm chocolate brownie with vanilla ice cream.", 180, True, 5, None),
        ("Rava Sheera", "Semolina pudding with ghee, sugar and dry fruits.", 80, True, 5, None),
        ("Kaju Katli (4 pcs)", "Cashew fudge diamonds.", 120, True, 2, None),
        ("Malpua", "Sweet fried pancakes soaked in syrup, with rabdi.", 130, True, 8, None),
        ("Phirni", "Chilled ground-rice pudding set in a clay pot.", 110, True, 3, None),
    ]),
]


def all_dishes():
    """Yield (category, station_key, name, description, price, is_veg, prep, image_slug)."""
    from django.utils.text import slugify
    for category, default_station, dishes in MENU:
        for name, desc, price, veg, prep, station in dishes:
            yield {
                "category": category,
                "station": station or default_station,
                "name": name,
                "description": desc,
                "price": price,
                "is_veg": veg,
                "prep": prep,
                "image_slug": slugify(name),
            }
