# Generated by Django 6.0.3 on 2026-03-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitemmodifiergroup'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucategory',
            options={'ordering': ['display_order']},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='menucategory',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modifier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='modifiergroup',
            name='max_select',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['tenant', 'outlet'], name='menu_menuca_tenant__2da424_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['tenant', 'outlet'], name='menu_menuit_tenant__9ccc00_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category'], name='menu_menuit_categor_acfcd4_idx'),
        ),
        migrations.AddIndex(
            model_name='modifiergroup',
            index=models.Index(fields=['tenant', 'outlet'], name='menu_modifi_tenant__591b54_idx'),
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'outlet', 'name'), name='unique_category_per_outlet'),
        ),
        migrations.AddConstraint(
            model_name='menuitemmodifiergroup',
            constraint=models.UniqueConstraint(fields=('menu_item', 'modifier_group'), name='unique_modifier_group_per_menu_item'),
        ),
    ]
