# Generated by Django 6.0.3 on 2026-03-13 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menucategory_options_alter_menuitem_options_and_more'),
        ('tenants', '0002_alter_outlet_options_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.kitchenstation'),
        ),
    ]
