# Generated by Django 6.0.3 on 2026-03-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_kitchenstation_menuitem_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchenstation',
            name='outlet',
        ),
        migrations.RemoveField(
            model_name='kitchenstation',
            name='tenant',
        ),
    ]
