# Generated by Django 6.0.3 on 2026-03-21 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_kitchenstation_outlet_and_more'),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup.kitchenstation'),
        ),
        migrations.DeleteModel(
            name='KitchenStation',
        ),
    ]
