# Generated by Django 6.0.3 on 2026-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menuitem_station_delete_kitchenstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='available_swiggy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_takeaway',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_zomato',
            field=models.BooleanField(default=True),
        ),
    ]
