# Generated by Django 6.0.3 on 2026-04-30 07:21

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/', validators=[core.validators.validate_image_size]),
        ),
    ]
