# Generated by Django 6.0.3 on 2026-04-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='estimated_prep_time',
            field=models.IntegerField(default=15, help_text='Estimated preparation time in minutes'),
        ),
    ]
