# Generated by Django 6.0.3 on 2026-05-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_menuitem_estimated_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
    ]
