# Generated by Django 6.0.3 on 2026-05-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_menuitem_is_veg'),
        ('setup', '0004_kitchenstation_printer_ip_and_more'),
        ('tenants', '0011_tenantfeatureoverride'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='menu_item_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='modifier',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='modifier_price_non_negative'),
        ),
    ]
