# Generated by Django 6.0.3 on 2026-05-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_bugfix_cascade_index_constraints'),
        ('setup', '0007_qz_tray_fields'),
        ('tenants', '0018_remove_tenant_tenants_ten_slug_63daca_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modifier',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='modifiergroup',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='modifier',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['station'], name='menuitem_station'),
        ),
    ]
