# Generated by Django 6.0.3 on 2026-05-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_modifier_options_alter_modifiergroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='parcel_charge',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Packing/parcel charge for this specific item. When any item in the order has this set, per-item charges override the outlet-level flat charge. Set to 0 to use the outlet default.', max_digits=6),
        ),
    ]
