# Generated by Django 6.0.8 on 2026-09-27 22:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_menuitem_parcel_charge'),
        ('setup', '0011_scheduledreportsubscription'),
        ('tenants', '0035_liquor_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='vat_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='menu.vatclass'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.CheckConstraint(condition=models.Q(('vat_class__isnull', True), ('gst_percentage', Decimal('0')), _connector='OR'), name='vat_item_has_no_gst'),
        ),
        migrations.AddIndex(
            model_name='vatclass',
            index=models.Index(fields=['tenant', 'outlet'], name='menu_vatcla_tenant__96b863_idx'),
        ),
        migrations.AddConstraint(
            model_name='vatclass',
            constraint=models.UniqueConstraint(fields=('outlet', 'name'), name='unique_vat_class_per_outlet'),
        ),
        migrations.AddConstraint(
            model_name='vatclass',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', Decimal('0')), ('rate__lte', Decimal('100'))), name='vat_class_rate_0_to_100'),
        ),
    ]
