# Generated by Django 6.0.8 on 2026-10-03 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_liquor_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='vat_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='menu.vatclass'),
        ),
    ]
