# Generated by Django 6.0.3 on 2026-03-04 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_kotbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='kot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.kotbatch'),
        ),
    ]
