# Generated by Django 6.0.3 on 2026-03-05 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_unique_open_order_per_table'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_created', 'Order Created'), ('item_added', 'Item Added'), ('kot_sent', 'KOT Sent'), ('kitchen_preparing', 'Kitchen Preparing'), ('kitchen_ready', 'Kitchen Ready'), ('payment_completed', 'Payment Completed'), ('order_cancelled', 'Order Cancelled')], max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_open_order_per_table',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant'], name='orders_orde_tenant__7c21a2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['outlet'], name='orders_orde_outlet__36f006_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['table'], name='orders_orde_table_i_37b1ad_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('tenant', 'outlet', 'table'), name='unique_open_order_per_table'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet'),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='orderlock',
            name='locked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderlock',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lock', to='orders.order'),
        ),
    ]
