# Generated by Django 6.0.3 on 2026-03-05 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderevent_orderlock_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='kotbatch',
            index=models.Index(fields=['status', 'created_at'], name='orders_kotb_status_9d8e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'outlet', 'status'], name='orders_orde_tenant__ee4b79_idx'),
        ),
    ]
