# Generated by Django 6.0.3 on 2026-03-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_kotbatch_orders_kotb_status_9d8e2e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kotbatch',
            name='kot_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='kotbatch',
            index=models.Index(fields=['kot_number'], name='orders_kotb_kot_num_4e21fb_idx'),
        ),
    ]
