# Generated by Django 6.0.3 on 2026-03-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_kotbatch_kot_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kotbatch',
            name='kot_number',
            field=models.IntegerField(),
        ),
    ]
