# Generated by Django 6.0.3 on 2026-03-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_kotbatch_kot_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyKOTCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
    ]
