# Generated by Django 6.0.3 on 2026-03-06 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_dailykotcounter'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kotbatch',
            name='outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kotbatch',
            name='station',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kotbatch',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='kotbatch',
            index=models.Index(fields=['tenant', 'outlet'], name='orders_kotb_tenant__8938f0_idx'),
        ),
        migrations.AddIndex(
            model_name='kotbatch',
            index=models.Index(fields=['tenant', 'outlet', 'status'], name='orders_kotb_tenant__a8ed5e_idx'),
        ),
    ]
