# Generated by Django 6.0.3 on 2026-03-06 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_modifiergroup_modifier'),
        ('orders', '0010_kotbatch_outlet_kotbatch_station_kotbatch_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.modifier')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='orders.orderitem')),
            ],
        ),
    ]
