# Generated by Django 6.0.3 on 2026-03-06 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitemmodifier'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='kotbatch',
            name='orders_kotb_status_9d8e2e_idx',
        ),
        migrations.RemoveIndex(
            model_name='kotbatch',
            name='orders_kotb_kot_num_4e21fb_idx',
        ),
        migrations.RemoveIndex(
            model_name='kotbatch',
            name='orders_kotb_tenant__8938f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='kotbatch',
            name='orders_kotb_tenant__a8ed5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_created_0e92de_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_tenant__ee4b79_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Kitchen'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='state',
            field=models.CharField(choices=[('free', 'Free'), ('ordering', 'Ordering'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('billing', 'Billing'), ('cleaning', 'Cleaning')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('billing', 'Billing'), ('paid', 'Paid'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AlterUniqueTogether(
            name='kotbatch',
            unique_together={('order', 'kot_number')},
        ),
    ]
