# Generated by Django 6.0.3 on 2026-03-10 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_kotbatch_orders_kotb_status_9d8e2e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='void_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('item_added', 'Item Added'), ('item_voided', 'Item Voided'), ('kot_sent', 'KOT Sent'), ('kitchen_preparing', 'Kitchen Preparing'), ('kitchen_ready', 'Kitchen Ready'), ('payment_completed', 'Payment Completed'), ('order_cancelled', 'Order Cancelled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to Kitchen'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('voided', 'Voided')], default='pending', max_length=20),
        ),
    ]
