# Generated by Django 6.0.3 on 2026-03-12 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menucategory_options_alter_menuitem_options_and_more'),
        ('orders', '0013_orderitem_notes_orderitem_void_reason_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('voided', 'Voided')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitemmodifier',
            name='modifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.modifier'),
        ),
        migrations.AddIndex(
            model_name='kotbatch',
            index=models.Index(fields=['tenant', 'outlet'], name='orders_kotb_tenant__8938f0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['order'], name='orders_orde_order_i_472423_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['status'], name='orders_orde_status_863d47_idx'),
        ),
        migrations.AddIndex(
            model_name='orderlock',
            index=models.Index(fields=['expires_at'], name='orders_orde_expires_d14ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order'], name='orders_paym_order_i_8c8d98_idx'),
        ),
        migrations.AddIndex(
            model_name='table',
            index=models.Index(fields=['tenant', 'outlet'], name='orders_tabl_tenant__d4508a_idx'),
        ),
        migrations.AddConstraint(
            model_name='waitercall',
            constraint=models.UniqueConstraint(condition=models.Q(('is_resolved', False)), fields=('table',), name='one_active_waiter_call_per_table'),
        ),
    ]
