# Generated by Django 6.0.3 on 2026-03-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_discount_total_order_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_complimentary',
            field=models.BooleanField(default=False),
        ),
    ]
