# Generated by Django 6.0.3 on 2026-03-25 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_payment_order'),
        ('tenants', '0002_alter_outlet_options_alter_tenant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='orderevent',
            name='after_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderevent',
            name='before_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('order_cancelled', 'Order Cancelled'), ('item_added', 'Item Added'), ('item_updated', 'Item Updated'), ('item_voided', 'Item Voided'), ('kot_sent', 'KOT Sent'), ('kitchen_preparing', 'Kitchen Preparing'), ('kitchen_ready', 'Kitchen Ready'), ('payment_added', 'Payment Added'), ('payment_completed', 'Payment Completed'), ('payment_refunded', 'Payment Refunded'), ('table_transferred', 'Table Transferred'), ('tables_merged', 'Tables Merged'), ('tables_unmerged', 'Tables Unmerged'), ('status_changed', 'Status Changed')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['event_type'], name='orders_orde_event_t_2ba24d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['created_at'], name='orders_orde_created_45dd1a_idx'),
        ),
    ]
