# Generated by Django 6.0.3 on 2026-03-30 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_orderevent_options_orderevent_after_state_and_more'),
        ('tenants', '0002_alter_outlet_options_alter_tenant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tablemerge',
            index=models.Index(fields=['tenant', 'outlet', 'is_active'], name='orders_tabl_tenant__4ffa85_idx'),
        ),
    ]
