# Generated by Django 6.0.3 on 2026-03-31 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_fix_tablemeta_index'),
        ('tenants', '0002_alter_outlet_options_alter_tenant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_messages', to='orders.order')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'outlet', 'is_resolved'], name='orders_kitc_tenant__89aa92_idx')],
            },
        ),
    ]
