# Generated by Django 6.0.3 on 2026-04-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='aggregator_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('takeaway', 'Takeaway'), ('zomato', 'Zomato'), ('swiggy', 'Swiggy'), ('uber_eats', 'Uber Eats'), ('web', 'Website')], default='dine_in', max_length=20),
        ),
    ]
