# Generated by Django 6.0.3 on 2026-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_aggregator_order_id_order_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_takeaway',
            field=models.BooleanField(default=False),
        ),
    ]
