# Generated by Django 6.0.3 on 2026-04-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_orderitem_is_takeaway'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='section',
            field=models.CharField(blank=True, default='Main Hall', max_length=100),
        ),
    ]
