# Generated by Django 6.0.3 on 2026-04-16 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_table_section'),
        ('setup', '0004_kitchenstation_printer_ip_and_more'),
        ('tenants', '0003_tenant_logo_tenant_sales_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailykotcounter',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet'),
        ),
        migrations.AddField(
            model_name='dailykotcounter',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='dailykotcounter',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='kotbatch',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kots', to='setup.kitchenstation'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='dailykotcounter',
            unique_together={('tenant', 'outlet', 'date')},
        ),
    ]
