# Generated by Django 6.0.3 on 2026-04-26 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_order_updated_at'),
        ('tenants', '0004_alter_tenant_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailykotcounter',
            name='outlet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailykotcounter',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('review', 'Needs Approval'), ('pending', 'Pending'), ('sent', 'Sent'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('voided', 'Voided')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('refund', 'Refund')], max_length=20),
        ),
    ]
