# Generated by Django 6.0.3 on 2026-04-30 06:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_dailykotcounter_outlet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_discount_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per-item discount percentage applied at billing', max_digits=5),
        ),
    ]
