# Generated by Django 6.0.3 on 2026-04-30 09:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_order_customer_name_order_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
