# Generated by Django 6.0.3 on 2026-05-08 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_dailyordercounter_orderevent_composite_idx'),
        ('tenants', '0009_outlet_closing_time_outlet_opening_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Happy Hours 20%' or 'Weekend Special'", max_length=120)),
                ('code', models.CharField(blank=True, help_text='Short code shown on bill (e.g. HH20)', max_length=30)),
                ('discount_type', models.CharField(choices=[('percentage', '% Off'), ('amount', '₹ Flat Off')], default='percentage', max_length=12)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['tenant', 'outlet', 'is_active'], name='orders_prom_tenant__495286_idx')],
            },
        ),
    ]
