# Generated by Django 6.0.3 on 2026-05-08 07:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_promo'),
        ('tenants', '0009_outlet_closing_time_outlet_opening_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='description',
            field=models.TextField(blank=True, help_text='T&C / internal notes visible to staff'),
        ),
        migrations.AddField(
            model_name='promo',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses', null=True),
        ),
        migrations.AddField(
            model_name='promo',
            name='min_order_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum order subtotal to apply this promo (0 = no minimum)', max_digits=10),
        ),
        migrations.AddField(
            model_name='promo',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promo',
            name='code',
            field=models.CharField(blank=True, help_text='Short code printed on bill (e.g. HH20). Unique per tenant.', max_length=30),
        ),
        migrations.AlterField(
            model_name='promo',
            name='name',
            field=models.CharField(help_text="e.g. 'Happy Hours 20%'", max_length=120),
        ),
        migrations.AlterField(
            model_name='promo',
            name='outlet',
            field=models.ForeignKey(blank=True, help_text='Leave blank to broadcast across all outlets of this tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet'),
        ),
        migrations.AddConstraint(
            model_name='promo',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('tenant', 'code'), name='unique_promo_code_per_tenant'),
        ),
    ]
