# Generated by Django 6.0.3 on 2026-05-09 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_promo_v2_alloutlet_caps'),
        ('tenants', '0010_tenant_subscription_end_date_tenant_subscription_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('aggregator_order_id', ''), _negated=True), ('aggregator_order_id__isnull', False)), fields=('outlet', 'aggregator_order_id'), name='unique_aggregator_order_per_outlet'),
        ),
    ]
