# Generated by Django 6.0.3 on 2026-05-09 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_order_unique_aggregator_order_per_outlet'),
        ('tenants', '0010_tenant_subscription_end_date_tenant_subscription_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='orders.order')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['outlet', 'date'], name='orders_toke_outlet__635998_idx')],
                'unique_together': {('outlet', 'token_number', 'date')},
            },
        ),
    ]
