# Generated by Django 6.0.3 on 2026-05-09 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_tokenorder'),
        ('tenants', '0010_tenant_subscription_end_date_tenant_subscription_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('dine_in', 'Dine In'), ('takeaway', 'Takeaway'), ('counter', 'Counter / QSR'), ('zomato', 'Zomato'), ('swiggy', 'Swiggy'), ('uber_eats', 'Uber Eats'), ('web', 'Website')], default='dine_in', max_length=20),
        ),
        migrations.AlterField(
            model_name='tokenorder',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='DailyTokenCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.PositiveIntegerField(default=0)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['outlet', 'date'], name='orders_dail_outlet__b22d4f_idx')],
                'unique_together': {('outlet', 'date')},
            },
        ),
    ]
