# Generated by Django 6.0.3 on 2026-05-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_alter_order_source_alter_tokenorder_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('zomato', 'Zomato'), ('swiggy', 'Swiggy'), ('uber_eats', 'Uber Eats'), ('web', 'Website'), ('refund', 'Refund')], max_length=20),
        ),
    ]
