# Generated by Django 6.0.3 on 2026-05-11 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_add_aggregator_payment_methods'),
        ('tenants', '0011_tenantfeatureoverride'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOnlineTokenCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tokenorder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='tokenorder',
            name='is_online',
            field=models.BooleanField(default=False, help_text='True for aggregator (Zomato/Swiggy/web) orders; False for walk-in counter orders.'),
        ),
        migrations.AlterUniqueTogether(
            name='tokenorder',
            unique_together={('outlet', 'token_number', 'date', 'is_online')},
        ),
        migrations.AddIndex(
            model_name='tokenorder',
            index=models.Index(fields=['outlet', 'date', 'is_online'], name='orders_toke_outlet__a9e5a6_idx'),
        ),
        migrations.AddField(
            model_name='dailyonlinetokencounter',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet'),
        ),
        migrations.AddField(
            model_name='dailyonlinetokencounter',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='dailyonlinetokencounter',
            index=models.Index(fields=['outlet', 'date'], name='orders_dail_outlet__1653e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyonlinetokencounter',
            unique_together={('outlet', 'date')},
        ),
    ]
