# Generated by Django 6.0.3 on 2026-05-20 18:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_fix_order_number_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parcel_surcharge',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra charge for parcel/takeaway orders. Added to grand_total.', max_digits=6),
        ),
    ]
