# Generated by Django 6.0.3 on 2026-05-23 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_modifier_options_alter_modifiergroup_options_and_more'),
        ('orders', '0042_order_parcel_surcharge'),
        ('setup', '0007_qz_tray_fields'),
        ('tenants', '0018_remove_tenant_tenants_ten_slug_63daca_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailyonlinetokencounter',
            name='orders_dail_outlet__1653e9_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailytokencounter',
            name='orders_dail_outlet__b22d4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_tenant__7c21a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_outlet__36f006_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='orders_orde_status_c6dd84_idx',
        ),
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_orde_status_863d47_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='order_table',
            old_name='orders_orde_table_i_37b1ad_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='gst_breakdown_cache',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='kotbatch',
            index=models.Index(fields=['tenant', 'outlet', 'status'], name='kotbatch_tenant_outlet_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'outlet', 'status'], name='order_tenant_outlet_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tenant', 'outlet', 'created_at'], name='order_tenant_outlet_date'),
        ),
        migrations.AddIndex(
            model_name='orderevent',
            index=models.Index(fields=['order', 'event_type'], name='orderevent_order_type'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orderitem_order'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'status'], name='orderitem_order_status'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['kot'], name='orderitem_kot'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paid_at'], name='payment_paid_at'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'method'], name='payment_order_method'),
        ),
    ]
