# Generated by Django 6.0.3 on 2026-05-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_add_printjob'),
        ('tenants', '0023_add_printjob'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='printjob',
            name='orders_prin_outlet__01004e_idx',
        ),
        migrations.AddIndex(
            model_name='printjob',
            index=models.Index(fields=['tenant', 'outlet', 'status', 'created_at'], name='orders_prin_tenant__e90431_idx'),
        ),
    ]
