# Generated by Django 6.0.3 on 2026-06-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_printjob_claimed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10),
        ),
    ]
