# Generated by Django 6.0.3 on 2026-06-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_alter_printjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='customer_complaint',
            field=models.CharField(blank=True, default='', help_text='What the customer said — visible to owner', max_length=500),
        ),
        migrations.AlterField(
            model_name='refund',
            name='reason',
            field=models.CharField(help_text="Manager's internal note for this refund", max_length=255),
        ),
    ]
