# Generated by Django 6.0.3 on 2026-06-19 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_refund_customer_complaint'),
        ('tenants', '0026_add_feature_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_id', models.CharField(max_length=100, unique=True)),
                ('image_url', models.URLField()),
                ('quoted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('expired', 'Expired'), ('closed', 'Closed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_qr_codes', to='orders.order')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.outlet')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='orders_razo_order_i_03566e_idx'), models.Index(fields=['status'], name='orders_razo_status_5c6673_idx')],
            },
        ),
    ]
