# Generated by Django 6.0.3 on 2026-06-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_razorpay_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderevent',
            name='event_type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('order_cancelled', 'Order Cancelled'), ('item_added', 'Item Added'), ('item_updated', 'Item Updated'), ('item_voided', 'Item Voided'), ('kot_sent', 'KOT Sent'), ('kitchen_preparing', 'Kitchen Preparing'), ('kitchen_ready', 'Kitchen Ready'), ('payment_added', 'Payment Added'), ('payment_completed', 'Payment Completed'), ('payment_refund_requested', 'Refund Requested'), ('payment_refunded', 'Payment Refunded'), ('payment_refund_rejected', 'Refund Rejected'), ('razorpay_overpaid_reconciliation', 'Razorpay Payment Needs Reconciliation'), ('razorpay_amount_mismatch', 'Razorpay Webhook Amount Mismatch'), ('table_transferred', 'Table Transferred'), ('tables_merged', 'Tables Merged'), ('tables_unmerged', 'Tables Unmerged'), ('status_changed', 'Status Changed')], max_length=50),
        ),
    ]
