# Generated by Django 6.0.3 on 2026-07-08 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0050_order_event_razorpay_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('reference', None), _negated=True), models.Q(('reference', ''), _negated=True)), fields=('reference',), name='unique_nonblank_payment_reference'),
        ),
    ]
