# Generated by Django 6.0.8 on 2026-09-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0060_delete_payments_models_state_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parcel_gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
