# Generated by Django 6.0.8 on 2026-09-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0061_tax_record_and_parcel_gst_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
    ]
