# Generated by Django 6.0.8 on 2026-09-27 22:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0062_order_lines_in_entry_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat_total',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tax_kind',
            field=models.CharField(choices=[('gst', 'GST'), ('vat', 'VAT')], db_default='gst', default='gst', max_length=3),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat_class_name',
            field=models.CharField(blank=True, db_default='', default='', max_length=40),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat_rate',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
