# Generated by Django 6.0.8 on 2026-09-28 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def keep_the_numbers_old_bills_were_printed_with(apps, schema_editor):
    """A bill already presented or paid keeps the number it was printed with
    (its order number). Orders still open get a new bill number when billed."""
    Order = apps.get_model("orders", "Order")
    Order.objects.filter(status__in=["billing", "paid", "closed"], bill_number__isnull=True).update(
        bill_number=F("order_number"))


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0063_liquor_vat'),
        ('tenants', '0037_outlet_bill_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=12)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'bill series',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='bill_number',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
        migrations.RunPython(keep_the_numbers_old_bills_were_printed_with, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('outlet', 'bill_number'), name='unique_bill_number_per_outlet'),
        ),
        migrations.AddField(
            model_name='billseries',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_series', to='tenants.outlet'),
        ),
        migrations.AddField(
            model_name='billseries',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddConstraint(
            model_name='billseries',
            constraint=models.UniqueConstraint(fields=('outlet', 'prefix'), name='unique_bill_series_per_outlet'),
        ),
    ]
