# Generated by Django 6.0.8 on 2026-10-03 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0064_bill_numbers'),
        ('promos', '0002_archive_promos'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promos.promo'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
