# Generated by Django 6.0.8 on 2026-10-03 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_liquor_vat'),
        ('orders', '0065_order_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='menu.menuitem'),
        ),
    ]
