# Generated by Django 6.0.8 on 2026-10-04: offers on bill lines (offers/engine.py)

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('orders', '0066_keep_sold_dishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='offer_total',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        # Lines already in the database keep no time (they use their order's):
        # added without a default first, so no existing row gets the deploy's
        # time, then the default for new lines.
        migrations.AddField(
            model_name='orderitem',
            name='added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='added_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='offers.offer'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer_discount',
            field=models.DecimalField(db_default=Decimal('0.00'), decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='offer_name',
            field=models.CharField(blank=True, db_default='', default='', max_length=80),
        ),
    ]
