# Generated by Django 6.0.3 on 2026-07-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenorder',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tokenorder',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
